<script lang="ts">
  // Beacon chat panel — Q&A against the currently picked PDF.
  //
  // Architecture:
  // - User picks a PDF (or it's pre-filled via the global `slab:open-recent`
  //   event the Reader panel uses).
  // - User types a question, hits Enter or Send.
  // - We invoke `slab_beacon_chat` with the conversation history.
  // - The reply lands as an assistant turn; cited pages are rendered as
  //   `[pN]` chips below the message — clicking one fires a custom event
  //   that the Reader panel can listen for (`slab:beacon-goto-page`).
  // - "New chat" clears history; "Change PDF" picks a new one (also clears).
  //
  // No streaming for v0.10.0 — single-shot buffered responses. Streaming
  // arrives in v0.10.1 once the Tauri event channel is wired.

  import { invoke } from "@tauri-apps/api/core";
  import { open } from "@tauri-apps/plugin-dialog";
  import { onMount, tick } from "svelte";
  import { basename, idle, type CmdResult, type Status } from "$lib/types";
  import { matches } from "$lib/keymap";
  import {
    slabBeaconVisionAsk,
    type BeaconChatTurn,
    type RectPts,
  } from "$lib/lens";
  import { registerBeaconNav } from "$lib/vim/beacon-adapter";

  type ChatTurn = {
    role: "user" | "assistant";
    content: string;
    pagesCited?: number[];
    model?: string;
    /** ms since epoch — for the human-readable timestamp tooltip. */
    ts: number;
    /** When true, this turn was generated by the vision pipeline rather
     *  than text Q&A. Lets the UI badge it distinctly. */
    vision?: boolean;
  };

  type BeaconChatReply = {
    content: string;
    model: string;
    pages_cited: number[];
    context_chars_used: number;
    context_chars_total: number;
    pages_total: number;
    pages_used: number;
  };

  type BeaconSummary = {
    content: string;
    model: string;
    length: SummaryLength;
    pages_used: number;
    pages_total: number;
  };

  type SummaryLength = "tldr" | "short" | "long";

  // ---------- Voice Mode: Listen (v1.9.1 STT) types ----------
  type SttEngineCapability = {
    id: string;
    installed: boolean;
    binary_path?: string;
  };
  type SttCapabilities = {
    engines: SttEngineCapability[];
    recorder_available: boolean;
  };
  type Transcript = {
    text: string;
    language?: string;
    duration_ms: number;
  };

  let pdfPath = $state<string | null>(null);
  let pdfPages = $state<number | null>(null);
  let question = $state("");
  let history = $state<ChatTurn[]>([]);
  let status = $state<Status>(idle);
  let lastStats = $state<{
    chars_used: number;
    chars_total: number;
    pages_used: number;
    pages_total: number;
  } | null>(null);

  let scrollContainer: HTMLDivElement | null = null;
  let inputEl: HTMLTextAreaElement | null = null;

  // ---------- Voice Mode: Listen (v1.9.1 STT) ----------
  //
  // Two-state mic button next to the Send button.
  //
  //   idle      → click starts recording. Mic icon, neutral colour.
  //   recording → click stops + transcribes. Pulses red. The returned
  //               transcript is appended to whatever's already in the
  //               textarea (so the user can pre-type a stem like
  //               "Summarise: " and dictate the rest).
  //
  // `sttCapable` gates the button entirely — if whisper-cli isn't on
  // PATH or no recorder is available, the mic is hidden rather than
  // shown as a broken affordance. The hint surfaces in BeaconVoicePanel
  // settings instead.
  let isRecording = $state(false);
  let isTranscribing = $state(false);
  let sttCapable = $state(false);
  let sttHint = $state<string | null>(null);
  // v1.9.2 — auto-send trigger settings loaded from ~/.slab/config.toml.
  // When `sttSendOnTrigger` is true and a transcript ends with
  // `sttTriggerWord` (word-boundary, case-insensitive, ignoring a
  // single trailing punctuation char), Beacon auto-submits the
  // composer after stripping the trigger phrase.
  let sttTriggerWord = $state<string | null>(null);
  let sttSendOnTrigger = $state(false);

  async function loadVoiceCfg() {
    try {
      // slab_beacon_config_read returns CmdResult<SlabConfig>; pull
      // the voice block. Quietly defaults to "off" if the call fails,
      // returns Err, or the section is missing.
      const res = await invoke<
        CmdResult<{
          beacon?: {
            voice?: {
              stt_trigger_word?: string | null;
              stt_send_on_trigger?: boolean;
            };
          };
        }>
      >("slab_beacon_config_read");
      if (res.kind === "ok") {
        sttTriggerWord = res.value?.beacon?.voice?.stt_trigger_word ?? null;
        sttSendOnTrigger = !!res.value?.beacon?.voice?.stt_send_on_trigger;
      }
    } catch {
      // Missing config just means defaults (off). Quiet.
    }
  }

  async function probeStt() {
    try {
      const caps = await invoke<SttCapabilities>(
        "slab_beacon_voice_stt_capabilities",
      );
      const engineInstalled =
        caps.engines.length > 0 && caps.engines[0].installed;
      sttCapable = engineInstalled && caps.recorder_available;
      if (!engineInstalled) {
        sttHint =
          "whisper-cli not installed — `brew install whisper-cpp` (macOS) or `apt install whisper-cpp` (Linux).";
      } else if (!caps.recorder_available) {
        sttHint =
          "No microphone recorder found — `brew install sox` (macOS) / `apt install alsa-utils` (Linux).";
      } else {
        sttHint = null;
      }
    } catch {
      sttCapable = false;
      sttHint = null;
    }
  }

  async function toggleMic() {
    if (isTranscribing) return; // race-guard
    if (isRecording) {
      // STOP path: transcribe + insert text into the prompt.
      isRecording = false;
      isTranscribing = true;
      status = { kind: "working", msg: "Transcribing…" };
      try {
        const res = await invoke<CmdResult<Transcript>>(
          "slab_beacon_voice_stt_stop",
        );
        if (res.kind === "ok") {
          const rawText = res.value.text.trim();

          // v1.9.2 — apply trigger-word detection BEFORE inserting
          // into the textarea. Mirrors the backend's pure
          // `detect_send_trigger` helper so the UI stays
          // unit-testable without an IPC round-trip. If the user
          // opted out we fall through to the v1.9.1 behaviour.
          let dictated = rawText;
          let shouldAutoSend = false;
          if (sttSendOnTrigger && sttTriggerWord && rawText) {
            const trig = sttTriggerWord.trim().toLowerCase();
            if (trig) {
              // Strip a single trailing punctuation char then check
              // the suffix with a whitespace-boundary requirement.
              const stripped = rawText.replace(/[.,!?;:]\s*$/, "").trimEnd();
              const lcStripped = stripped.toLowerCase();
              if (lcStripped.endsWith(trig)) {
                const prefixLen = lcStripped.length - trig.length;
                const boundaryOk =
                  prefixLen === 0 || /\s/.test(stripped[prefixLen - 1]);
                if (boundaryOk) {
                  dictated = stripped.slice(0, prefixLen).trimEnd();
                  shouldAutoSend = true;
                }
              }
            }
          }

          if (dictated) {
            question = question
              ? `${question.trimEnd()} ${dictated}`
              : dictated;
          }
          const dur = (res.value.duration_ms / 1000).toFixed(1);
          if (shouldAutoSend) {
            // Auto-send path: brief status flip then fire send().
            status = { kind: "ok", msg: `Heard ${dur}s — sending…` };
            await tick();
            await send();
          } else {
            status = dictated
              ? { kind: "ok", msg: `Heard ${dur}s — ready to send.` }
              : { kind: "err", msg: "Couldn't hear anything." };
            // Focus the textarea so the user can keep typing or hit Enter.
            await tick();
            inputEl?.focus();
            // Place caret at the end of the now-extended text.
            if (inputEl) {
              const len = inputEl.value.length;
              inputEl.setSelectionRange(len, len);
            }
          }
        } else {
          status = { kind: "err", msg: res.message };
        }
      } catch (e) {
        status = { kind: "err", msg: `${e}` };
      } finally {
        isTranscribing = false;
      }
    } else {
      // START path: spawn the recorder.
      try {
        const res = await invoke<CmdResult<null>>(
          "slab_beacon_voice_stt_start",
          { engine: null },
        );
        if (res.kind === "ok") {
          isRecording = true;
          status = { kind: "working", msg: "Recording… click mic to stop, ESC to discard." };
        } else {
          status = { kind: "err", msg: res.message };
        }
      } catch (e) {
        status = { kind: "err", msg: `${e}` };
      }
    }
  }

  // v1.9.2 — discard the in-flight recording. Called from ESC and the
  // mic's context-menu. Idempotent: safe to call when not recording.
  async function cancelMic() {
    if (!isRecording) return;
    try {
      await invoke<CmdResult<null>>("slab_beacon_voice_stt_cancel");
    } catch (e) {
      // Best-effort — if the backend hiccups we still clear the UI.
      console.warn("voice_stt_cancel failed:", e);
    }
    isRecording = false;
    isTranscribing = false;
    status = { kind: "ok", msg: "Recording discarded." };
  }

  // Subscribe to the same recent-file channel the Reader uses, so opening a
  // PDF from the command palette can also pre-fill Beacon.
  function onOpenRecent(e: Event) {
    const detail = (e as CustomEvent).detail as { path: string } | undefined;
    if (!detail?.path) return;
    setPdf(detail.path);
  }

  onMount(() => {
    window.addEventListener("slab:open-recent", onOpenRecent);
    window.addEventListener("slab:beacon-vision-rect", onVisionRect);
    // Glass II (v1.2.0 Slice 3 second half) — Vim adapter wiring.
    window.addEventListener("slab:vim-beacon:scroll", onVimScroll as EventListener);
    window.addEventListener("slab:vim-beacon:scroll-edge", onVimScrollEdge as EventListener);
    window.addEventListener("slab:vim-beacon:focus-input", onVimFocusInput);
    window.addEventListener("slab:vim-beacon:blur-input", onVimBlurInput);
    window.addEventListener("slab:vim-beacon:reset-chat", onVimResetChat);
    const unregister = registerBeaconNav();
    // v1.9.1 — probe STT capabilities so we know whether to show the
    // mic button. Cheap (a few $PATH stat calls) and fire-and-forget.
    probeStt();
    loadVoiceCfg();
    return () => {
      window.removeEventListener("slab:open-recent", onOpenRecent);
      window.removeEventListener("slab:beacon-vision-rect", onVisionRect);
      window.removeEventListener("slab:vim-beacon:scroll", onVimScroll as EventListener);
      window.removeEventListener("slab:vim-beacon:scroll-edge", onVimScrollEdge as EventListener);
      window.removeEventListener("slab:vim-beacon:focus-input", onVimFocusInput);
      window.removeEventListener("slab:vim-beacon:blur-input", onVimBlurInput);
      window.removeEventListener("slab:vim-beacon:reset-chat", onVimResetChat);
      unregister();
    };
  });

  async function setPdf(p: string) {
    pdfPath = p;
    history = [];
    status = idle;
    pdfPages = null;
    lastStats = null;
    // Best-effort page count for the header; failures are silent.
    try {
      const res = await invoke<CmdResult<number>>("slab_page_count", {
        input: p,
      });
      if (res.kind === "ok") pdfPages = res.value;
    } catch {
      /* ignore */
    }
  }

  async function pickPdf() {
    const picked = await open({
      multiple: false,
      filters: [{ name: "PDF", extensions: ["pdf"] }],
    });
    if (typeof picked !== "string") return;
    await setPdf(picked);
  }

  function resetChat() {
    history = [];
    status = idle;
    lastStats = null;
    question = "";
  }

  async function send() {
    const q = question.trim();
    if (!pdfPath) {
      status = { kind: "err", msg: "Pick a PDF first." };
      return;
    }
    if (!q) return;
    if (status.kind === "working") return;

    // Push user turn immediately for snappy UX.
    history = [
      ...history,
      { role: "user", content: q, ts: Date.now() },
    ];
    question = "";
    status = { kind: "working", msg: "Beacon is reading the PDF…" };
    await scrollToBottom();

    // Build the wire-format history. Skip the just-pushed user turn since
    // the backend treats `question` separately.
    const wireHistory = history.slice(0, -1).map((t) => ({
      role: t.role,
      content: t.content,
    }));

    try {
      const res = await invoke<CmdResult<BeaconChatReply>>("slab_beacon_chat", {
        pdfPath,
        question: q,
        history: wireHistory,
        maxContextChars: null,
      });
      if (res.kind === "ok") {
        const r = res.value;
        history = [
          ...history,
          {
            role: "assistant",
            content: r.content,
            pagesCited: r.pages_cited,
            model: r.model,
            ts: Date.now(),
          },
        ];
        lastStats = {
          chars_used: r.context_chars_used,
          chars_total: r.context_chars_total,
          pages_used: r.pages_used,
          pages_total: r.pages_total,
        };
        status = idle;
      } else {
        status = { kind: "err", msg: friendlyError(res.message) };
      }
    } catch (e) {
      status = { kind: "err", msg: String(e) };
    } finally {
      await scrollToBottom();
      inputEl?.focus();
    }
  }

  /** Map raw provider errors → friendly hints. */
  function friendlyError(msg: string): string {
    const m = msg.toLowerCase();
    if (m.includes("provider unavailable")) {
      if (m.includes("missing api key")) return msg;
      return (
        msg +
        "  ·  Hint: start Ollama (`ollama serve`) or switch provider in Settings."
      );
    }
    return msg;
  }

  function onKeydown(e: KeyboardEvent) {
    // v1.9.2 — ESC while recording cancels the in-flight take. Has
    // priority over send shortcuts so a panicked ESC always works.
    if (e.key === "Escape" && isRecording) {
      e.preventDefault();
      cancelMic();
      return;
    }
    // Enter sends (Shift+Enter newlines).
    // The customisable `beacon.send` action (defaults to Mod+Enter) also
    // sends — that lets users rebind to e.g. Mod+Shift+Enter if they want
    // Enter to *always* mean newline in long-form prompts. Both checks
    // are honoured so existing muscle memory keeps working.
    if (matches(e, "beacon.send")) {
      e.preventDefault();
      send();
      return;
    }
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  async function scrollToBottom() {
    await tick();
    if (scrollContainer) {
      scrollContainer.scrollTop = scrollContainer.scrollHeight;
    }
  }

  // ---------- Vim adapter event handlers (Glass II Slice 3 second half) ----------

  type ScrollDetail = {
    kind: "line" | "half" | "full";
    direction: "up" | "down";
    count?: number;
  };

  function onVimScroll(e: CustomEvent<ScrollDetail>) {
    if (!scrollContainer) return;
    const d = e.detail;
    const h = scrollContainer.clientHeight;
    let step = 80; // line
    if (d.kind === "half") step = Math.max(120, Math.floor(h * 0.5));
    else if (d.kind === "full") step = Math.max(200, h - 40);
    const count = Math.max(1, d.count ?? 1);
    const delta = step * count * (d.direction === "down" ? 1 : -1);
    scrollContainer.scrollBy({ top: delta, behavior: "smooth" });
  }

  function onVimScrollEdge(e: CustomEvent<{ target: "first" | "last" }>) {
    if (!scrollContainer) return;
    if (e.detail.target === "first") {
      scrollContainer.scrollTo({ top: 0, behavior: "smooth" });
    } else {
      scrollContainer.scrollTo({
        top: scrollContainer.scrollHeight,
        behavior: "smooth",
      });
    }
  }

  function onVimFocusInput() {
    inputEl?.focus();
  }

  function onVimBlurInput() {
    inputEl?.blur();
  }

  function onVimResetChat() {
    resetChat();
  }

  function jumpToPage(p: number) {
    if (!pdfPath) return;
    window.dispatchEvent(
      new CustomEvent("slab:beacon-goto-page", {
        detail: { path: pdfPath, page: p },
      }),
    );
  }

  function fmtPct(used: number, total: number): string {
    if (total === 0) return "0%";
    return `${Math.round((used / total) * 100)}%`;
  }

  /** Run a summary call and push the result as an assistant turn. */
  async function summarize(length: SummaryLength) {
    if (!pdfPath) {
      status = { kind: "err", msg: "Pick a PDF first." };
      return;
    }
    if (status.kind === "working") return;
    const label =
      length === "tldr" ? "TL;DR" : length === "short" ? "Summary" : "Detailed summary";
    history = [
      ...history,
      { role: "user", content: `▶ ${label} of this PDF`, ts: Date.now() },
    ];
    status = { kind: "working", msg: `Beacon is reading the PDF…` };
    await scrollToBottom();
    try {
      const res = await invoke<CmdResult<BeaconSummary>>("slab_beacon_summary", {
        pdfPath,
        length,
        maxContextChars: null,
      });
      if (res.kind === "ok") {
        const r = res.value;
        history = [
          ...history,
          {
            role: "assistant",
            content: r.content,
            model: r.model,
            ts: Date.now(),
          },
        ];
        lastStats = {
          chars_used: 0,
          chars_total: 0,
          pages_used: r.pages_used,
          pages_total: r.pages_total,
        };
        status = idle;
      } else {
        status = { kind: "err", msg: friendlyError(res.message) };
      }
    } catch (e) {
      status = { kind: "err", msg: String(e) };
    } finally {
      await scrollToBottom();
    }
  }

  // Sample prompts — the empty-state nudges users toward useful things.
  const samplePrompts: string[] = [
    "Summarize this PDF in 3 bullets.",
    "What are the main conclusions?",
    "Who is the intended audience?",
    "Are there any dates, names, or numbers I should know about?",
  ];

  // ---------- Vision Q&A (v0.13.0 Slice 5) ----------

  let visionOpen = $state(false);
  let visionPage = $state(1);
  let visionQuestion = $state("");
  let visionRect = $state<RectPts | null>(null);

  /** Toggle the vision composer drawer. Defaults page to 1 (or the last
   *  vision target if reusing the panel). */
  function toggleVision() {
    visionOpen = !visionOpen;
    if (visionOpen) {
      if (pdfPages && (visionPage < 1 || visionPage > pdfPages)) {
        visionPage = 1;
      }
      // Focus the question field next tick.
      tick().then(() => {
        const el = document.querySelector<HTMLTextAreaElement>(
          ".vision-composer textarea",
        );
        el?.focus();
      });
    }
  }

  function clearVisionRect() {
    visionRect = null;
  }

  /** Build wire-format history. Only text-mode turns are sent (vision turns
   *  have no text equivalent the provider can reuse). */
  function buildVisionHistory(): BeaconChatTurn[] {
    return history
      .filter((t) => !t.vision)
      .map((t) => ({ role: t.role, content: t.content }));
  }

  async function askVision() {
    const q = visionQuestion.trim();
    if (!pdfPath) {
      status = { kind: "err", msg: "Pick a PDF first." };
      return;
    }
    if (!q) return;
    if (status.kind === "working") return;
    const pageNum = Math.max(1, Math.min(pdfPages ?? 9999, visionPage | 0));

    const userPrefix = visionRect ? "🔍 (region) " : "👁 ";
    history = [
      ...history,
      {
        role: "user",
        content: `${userPrefix}p${pageNum}: ${q}`,
        ts: Date.now(),
        vision: true,
      },
    ];
    visionQuestion = "";
    status = { kind: "working", msg: "Beacon is looking at the page…" };
    await scrollToBottom();

    try {
      const reply = await slabBeaconVisionAsk({
        pdfPath,
        page: pageNum,
        rectPts: visionRect,
        prompt: q,
        history: buildVisionHistory(),
      });
      history = [
        ...history,
        {
          role: "assistant",
          content: reply.content,
          model: reply.model,
          pagesCited: [reply.page],
          ts: Date.now(),
          vision: true,
        },
      ];
      status = idle;
      visionRect = null;
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      status = { kind: "err", msg: friendlyVisionError(msg) };
    } finally {
      await scrollToBottom();
    }
  }

  function friendlyVisionError(msg: string): string {
    const m = msg.toLowerCase();
    if (m.includes("vision unsupported")) {
      return (
        msg +
        "  ·  Hint: vision needs Ollama with llava (`ollama pull llava:7b`)." +
        " Switch provider in Settings → Beacon."
      );
    }
    if (m.includes("pdftoppm")) {
      return (
        msg +
        "  ·  Hint: install poppler (`brew install poppler`) so Slab can rasterize pages."
      );
    }
    return friendlyError(msg);
  }

  function onVisionKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      e.preventDefault();
      visionOpen = false;
      return;
    }
    if (e.key === "Enter" && !e.shiftKey && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      askVision();
    }
  }

  // Listen for a future selection event that the Reader panel will dispatch
  // once rect selection lands (v0.13.1). For now this is a no-op safety net:
  // if a sibling component emits `slab:beacon-vision-rect` with a rect, we
  // capture it and pre-fill the vision composer.
  function onVisionRect(e: Event) {
    const detail = (e as CustomEvent).detail as
      | { page?: number; rect?: RectPts; path?: string }
      | undefined;
    if (!detail) return;
    if (detail.path && detail.path !== pdfPath) return;
    if (detail.page) visionPage = detail.page;
    if (detail.rect) visionRect = detail.rect;
    visionOpen = true;
  }
</script>

<header class="content-header">
  <h1>Beacon <span class="beta-tag">beta · v0.10.0</span></h1>
  <p class="subtitle">
    Chat with your PDF locally. Beacon runs on Ollama by default —
    your document never leaves the machine.
  </p>
</header>

<section class="beacon">
  {#if !pdfPath}
    <button class="dropzone" onclick={pickPdf}>
      <span class="dz-icon">✨</span>
      <span class="dz-title">Pick a PDF to chat with</span>
      <span class="dz-hint">
        Beacon reads the full text, lets you ask questions, and cites
        the pages it pulled the answer from.
      </span>
    </button>
  {:else}
    <div class="file-card">
      <div>
        <div class="file-name">{basename(pdfPath)}</div>
        <div class="file-meta">
          {pdfPages !== null ? `${pdfPages} pages` : "loading…"}
          {#if lastStats}
            · last answer used pages 1–{lastStats.pages_used} of
            {lastStats.pages_total}
            {#if lastStats.chars_total > 0}
              ({fmtPct(lastStats.chars_used, lastStats.chars_total)} of text)
            {/if}
          {/if}
        </div>
      </div>
      <div class="card-actions">
        <button class="ghost" onclick={resetChat} disabled={history.length === 0}>
          New chat
        </button>
        <button class="ghost" onclick={pickPdf}>Change PDF</button>
      </div>
    </div>

    <div class="quick-actions">
      <span class="qa-label">Quick:</span>
      <button
        class="qa-chip"
        onclick={() => summarize("tldr")}
        disabled={status.kind === "working"}
        title="One-sentence summary"
      >
        ✦ TL;DR
      </button>
      <button
        class="qa-chip"
        onclick={() => summarize("short")}
        disabled={status.kind === "working"}
        title="Paragraph summary"
      >
        ✦ Summarize
      </button>
      <button
        class="qa-chip"
        onclick={() => summarize("long")}
        disabled={status.kind === "working"}
        title="5-bullet detailed summary"
      >
        ✦ Detailed
      </button>
      <span class="qa-divider" aria-hidden="true"></span>
      <button
        class="qa-chip vision"
        class:active={visionOpen}
        onclick={toggleVision}
        disabled={status.kind === "working"}
        title="Ask about a page visually (charts, diagrams, layouts)"
      >
        👁 Vision
      </button>
    </div>

    {#if visionOpen}
      <div class="vision-composer">
        <div class="vc-row">
          <label class="vc-label" for="vision-page">Page</label>
          <input
            id="vision-page"
            type="number"
            min="1"
            max={pdfPages ?? undefined}
            bind:value={visionPage}
            class="vc-page"
          />
          {#if pdfPages}
            <span class="vc-hint">of {pdfPages}</span>
          {/if}
          {#if visionRect}
            <span class="vc-rect-chip" title="Region: {Math.round(visionRect.x)},{Math.round(visionRect.y)} {Math.round(visionRect.width)}×{Math.round(visionRect.height)}pt">
              🔍 region
              <button
                class="vc-rect-clear"
                onclick={clearVisionRect}
                title="Clear region — ask about the whole page"
                aria-label="Clear region"
              >×</button>
            </span>
          {/if}
          <button
            class="vc-close"
            onclick={() => (visionOpen = false)}
            title="Close vision composer (Esc)"
            aria-label="Close vision composer"
          >×</button>
        </div>
        <textarea
          bind:value={visionQuestion}
          onkeydown={onVisionKeydown}
          rows="2"
          aria-label="Vision question"
          placeholder="Ask about this page… e.g. 'What does the chart show?' (⌘/Ctrl+Enter to send, Esc to close)"
          disabled={status.kind === "working"}
        ></textarea>
        <div class="vc-actions">
          <span class="vc-model">via llava:7b (local, default)</span>
          <button
            class="primary"
            onclick={askVision}
            disabled={status.kind === "working" || visionQuestion.trim().length === 0}
          >
            {status.kind === "working" ? "…" : "Ask Beacon 👁"}
          </button>
        </div>
      </div>
    {/if}

    <div class="chat-scroll" bind:this={scrollContainer}>
      {#if history.length === 0}
        <div class="empty">
          <div class="empty-title">Ask Beacon anything about this PDF.</div>
          <div class="empty-sample-grid">
            {#each samplePrompts as p (p)}
              <button class="sample" onclick={() => (question = p)}>
                {p}
              </button>
            {/each}
          </div>
        </div>
      {:else}
        {#each history as turn, i (i)}
          <div class="turn" class:user={turn.role === "user"} class:assistant={turn.role === "assistant"}>
            <div class="turn-role">
              {turn.role === "user" ? "You" : "Beacon"}
              {#if turn.role === "assistant" && turn.vision}
                <span class="turn-vision-badge" title="Generated from a page image">👁 vision</span>
              {/if}
              {#if turn.role === "assistant" && turn.model}
                <span class="turn-model">· {turn.model}</span>
              {/if}
            </div>
            <div class="turn-body">{turn.content}</div>
            {#if turn.role === "assistant" && turn.pagesCited && turn.pagesCited.length > 0}
              <div class="cites">
                <span class="cites-label">Pages cited:</span>
                {#each turn.pagesCited as p (p)}
                  <button class="cite-chip" onclick={() => jumpToPage(p)} title="Jump to page {p}">
                    p{p}
                  </button>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      {/if}

      {#if status.kind === "working"}
        <div class="turn assistant working">
          <div class="turn-role">Beacon</div>
          <div class="turn-body italic">{status.msg}</div>
        </div>
      {/if}
    </div>

    {#if status.kind === "err"}
      <div class="status err">✕ {status.msg}</div>
    {/if}

    <div class="composer">
      <textarea
        bind:this={inputEl}
        bind:value={question}
        onkeydown={onKeydown}
        rows="2"
        aria-label="Chat with Beacon"
        placeholder="Ask about this PDF… (Enter to send, Shift+Enter for newline)"
        disabled={status.kind === "working"}
      ></textarea>
      {#if sttCapable}
        <button
          type="button"
          class="mic"
          class:recording={isRecording}
          onclick={toggleMic}
          oncontextmenu={(e) => {
            e.preventDefault();
            if (isRecording) cancelMic();
          }}
          disabled={isTranscribing}
          title={isRecording
            ? "Stop recording (transcribes). ESC or right-click to discard."
            : "Dictate your question (whisper.cpp, on-device)"}
          aria-label={isRecording ? "Stop recording" : "Start dictation"}
        >
          {#if isTranscribing}
            ⏳
          {:else if isRecording}
            ◼
          {:else}
            🎙
          {/if}
        </button>
      {/if}
      <button
        class="primary"
        onclick={send}
        disabled={status.kind === "working" || question.trim().length === 0}
      >
        {status.kind === "working" ? "…" : "Send"}
      </button>
    </div>
  {/if}
</section>

<style>
  .beacon {
    display: flex;
    flex-direction: column;
    gap: 12px;
    min-height: 0;
    flex: 1;
  }
  .beta-tag {
    font-size: 10px;
    color: var(--accent);
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: 4px;
    padding: 1px 6px;
    margin-left: 8px;
    font-weight: 500;
    letter-spacing: 0.4px;
    text-transform: uppercase;
    vertical-align: middle;
  }

  .card-actions {
    display: flex;
    gap: 6px;
  }

  .quick-actions {
    display: flex;
    align-items: center;
    gap: 6px;
    flex-wrap: wrap;
  }
  .qa-label {
    font-size: 11px;
    color: var(--text-3);
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-right: 4px;
  }
  .qa-chip {
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: 14px;
    padding: 4px 11px;
    font-size: 12px;
    color: var(--text-2);
    cursor: pointer;
    transition: all 80ms ease;
  }
  .qa-chip:hover:not(:disabled) {
    background: var(--bg-3);
    color: var(--accent);
    border-color: var(--accent);
  }
  .qa-chip:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .qa-divider {
    width: 1px;
    height: 14px;
    background: var(--border);
    margin: 0 4px;
  }
  .qa-chip.vision.active {
    background: var(--bg-3);
    color: var(--accent);
    border-color: var(--accent);
  }

  .vision-composer {
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 10px 12px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    animation: vc-slide-in 120ms ease-out;
  }
  @keyframes vc-slide-in {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
  .vc-row {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 12px;
  }
  .vc-label {
    color: var(--text-3);
    text-transform: uppercase;
    letter-spacing: 0.5px;
    font-size: 10px;
    font-weight: 600;
  }
  .vc-page {
    width: 70px;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 4px;
    padding: 4px 8px;
    font-size: 12px;
    color: var(--text);
  }
  .vc-hint {
    color: var(--text-3);
    font-size: 11px;
  }
  .vc-rect-chip {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    color: var(--accent);
    border: 1px solid color-mix(in srgb, var(--accent) 30%, transparent);
    border-radius: 12px;
    padding: 2px 4px 2px 9px;
    font-size: 11px;
    font-weight: 500;
  }
  .vc-rect-clear {
    background: transparent;
    border: 0;
    color: inherit;
    cursor: pointer;
    font-size: 14px;
    line-height: 1;
    padding: 0 4px;
    border-radius: 50%;
  }
  .vc-rect-clear:hover {
    background: color-mix(in srgb, var(--accent) 22%, transparent);
  }
  .vc-close {
    margin-left: auto;
    background: transparent;
    border: 0;
    color: var(--text-3);
    cursor: pointer;
    font-size: 18px;
    line-height: 1;
    padding: 0 6px;
    border-radius: 4px;
  }
  .vc-close:hover {
    background: var(--bg-3);
    color: var(--text);
  }
  .vision-composer textarea {
    width: 100%;
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 8px 10px;
    font: inherit;
    font-size: 13px;
    color: var(--text);
    resize: vertical;
    min-height: 48px;
  }
  .vision-composer textarea:focus {
    outline: none;
    border-color: var(--accent);
  }
  .vc-actions {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .vc-model {
    color: var(--text-3);
    font-size: 11px;
    font-style: italic;
  }
  .vc-actions .primary {
    margin-left: auto;
  }

  .chat-scroll {
    flex: 1;
    min-height: 200px;
    overflow-y: auto;
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 14px 16px;
    display: flex;
    flex-direction: column;
    gap: 14px;
  }

  .empty {
    color: var(--text-3);
    text-align: center;
    padding: 20px 0;
  }
  .empty-title {
    font-size: 13px;
    margin-bottom: 12px;
  }
  .empty-sample-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    max-width: 540px;
    margin: 0 auto;
  }
  .sample {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 9px 12px;
    text-align: left;
    font-size: 12px;
    color: var(--text-2);
    cursor: pointer;
    transition: all 80ms ease;
  }
  .sample:hover {
    background: var(--bg-3);
    color: var(--text);
    border-color: var(--accent);
  }

  .turn {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .turn-role {
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    color: var(--text-3);
    font-weight: 600;
  }
  .turn-model {
    color: var(--text-3);
    text-transform: none;
    letter-spacing: 0;
    font-weight: 400;
    font-size: 10px;
    margin-left: 2px;
  }
  .turn-vision-badge {
    display: inline-block;
    margin-left: 6px;
    padding: 1px 6px;
    font-size: 9px;
    font-weight: 600;
    letter-spacing: 0.4px;
    text-transform: uppercase;
    color: var(--accent);
    background: color-mix(in srgb, var(--accent) 14%, transparent);
    border: 1px solid color-mix(in srgb, var(--accent) 30%, transparent);
    border-radius: 3px;
    vertical-align: middle;
  }
  .turn-body {
    font-size: 13px;
    line-height: 1.55;
    color: var(--text);
    white-space: pre-wrap;
    word-break: break-word;
  }
  .turn.user .turn-body {
    background: var(--bg-3);
    border-left: 2px solid var(--accent);
    padding: 8px 12px;
    border-radius: 4px;
    color: var(--text);
  }
  .turn.working .turn-body {
    color: var(--text-3);
  }
  .italic {
    font-style: italic;
  }

  .cites {
    margin-top: 4px;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 6px;
  }
  .cites-label {
    font-size: 10px;
    color: var(--text-3);
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  .cite-chip {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 2px 9px;
    font-size: 11px;
    color: var(--accent);
    cursor: pointer;
    font-variant-numeric: tabular-nums;
    transition: all 80ms ease;
  }
  .cite-chip:hover {
    background: var(--accent);
    color: var(--bg);
    border-color: var(--accent);
  }

  .composer {
    display: flex;
    gap: 8px;
    align-items: stretch;
  }
  .composer textarea {
    flex: 1;
    resize: vertical;
    min-height: 44px;
    max-height: 240px;
    background: var(--bg-2);
    color: var(--text);
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 8px 10px;
    font-family: inherit;
    font-size: 13px;
    line-height: 1.45;
  }
  .composer textarea:focus {
    outline: none;
    border-color: var(--accent);
  }
  .composer .primary {
    align-self: stretch;
    padding: 0 18px;
  }
  /* v1.9.1 — Voice Mode: Listen. The mic button sits between the
     textarea and the Send button. Idle: ghost-style icon. Recording:
     red fill with a subtle pulse so the user has constant feedback
     that audio is still being captured. */
  .composer .mic {
    align-self: stretch;
    padding: 0 12px;
    min-width: 42px;
    font-size: 16px;
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: var(--r-sm, 6px);
    color: var(--text-2);
    cursor: pointer;
    transition:
      background 100ms ease,
      border-color 100ms ease,
      color 100ms ease;
  }
  .composer .mic:hover:not(:disabled) {
    background: var(--bg-3);
    border-color: var(--accent);
    color: var(--accent);
  }
  .composer .mic:disabled {
    opacity: 0.55;
    cursor: not-allowed;
  }
  .composer .mic.recording {
    background: #ef4444;
    border-color: #ef4444;
    color: white;
    animation: mic-pulse 1.4s ease-in-out infinite;
  }
  @keyframes mic-pulse {
    0%,
    100% {
      box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.6);
    }
    50% {
      box-shadow: 0 0 0 6px rgba(239, 68, 68, 0);
    }
  }
</style>
