//! Hopper backfill — apply current rules to PDFs already sitting in a
//! watched folder (v3.22.0 "Hopper Loop").
//!
//! v3.20 shipped folder watching. v3.21 shipped per-folder rules. This
//! module closes the loop with **batch backfill**: when a user finishes
//! editing a rule list they almost always have hundreds of legacy PDFs
//! already in the folder that the live watcher never saw. Backfill
//! evaluates those files against the current rule chain and reports
//! exactly what would happen — file by file — *before* committing any
//! filesystem move. The UI ("Test on this folder…") renders the
//! [`BackfillReport`] as a table; the user clicks Apply and we call
//! [`execute_backfill`] to actually perform the moves idempotently.
//!
//! ## Why this exists
//!
//! - Paralegals routinely have a 2,000-PDF discovery folder that needs
//!   to be sliced into per-matter sub-folders. Adobe Acrobat has no
//!   equivalent — every batch action is per-file dialog hell.
//! - Hazel ($42) can do generic moves but is mac-only and has no
//!   PDF-aware predicates (page count, text contains).
//! - Slab's wedge: enterprise-grade local PDF automation, zero cloud.
//!
//! ## Buy-button test
//!
//! - **Pick-us**: "drop 4,000 PDFs in inbox, get routed by my rules in
//!   30 seconds" — Acrobat literally cannot.
//! - **Tell-a-friend**: the dry-run preview table itself is a wow.
//!
//! ## Module layout
//!
//! - [`plan_backfill`] — pure-fn walk + rule evaluation, no FS mutation.
//! - [`execute_backfill`] — commit a previously-planned report.
//! - [`BackfillReport`] / [`PlannedAction`] / [`BackfillRun`] — typed
//!   results that the UI renders directly.

use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use super::registry::Watch;
use super::rules::{evaluate_rules, Rule, RuleContext};

// ─── Types ────────────────────────────────────────────────────────────

/// What `plan_backfill` decided would happen to a single file. The UI
/// renders one of these per table row; the user can deselect any row
/// before clicking Apply.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PlannedAction {
    /// Absolute path to the source file the planner inspected.
    pub source_path: String,
    /// Display-only file size in bytes (lets the table sort by size).
    pub size_bytes: u64,
    /// Name of the rule that matched, if any. `None` means the watch
    /// defaults applied (still routes — the action will be `Move`).
    pub matched_rule: Option<String>,
    /// Where the file would land if `execute_backfill` runs on this
    /// report. `None` only for `Skip` actions (e.g. probe error).
    pub destination: Option<String>,
    /// What [`execute_backfill`] will do with this entry.
    pub action: ActionKind,
    /// Human-readable explanation — shown in the UI tooltip and used
    /// in the JSON report for audit trails. Always populated.
    pub reason: String,
}

/// Discriminator for [`PlannedAction::action`]. `kebab-case` on the
/// wire to match the rest of the Hopper TS shapes.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum ActionKind {
    /// File will be moved to `destination` (recipe applied first if the
    /// resolved routing has one — but v1 backfill is **rename + move
    /// only**, no recipe execution, see module docs).
    Move,
    /// Reserved for a future "preserve original, write copy" mode. Not
    /// emitted by v3.22 but the variant is part of the wire contract so
    /// the UI is forward-compatible.
    Copy,
    /// Skipped at plan time — probe error, unreadable file, etc. The
    /// `reason` field explains why; this row will be greyed out in the UI.
    Skip,
    /// No rule matched **and** the watch has no default `output_dir`
    /// (impossible today — `output_dir` is required — but variant kept
    /// for forward-compat with optional output_dir watches).
    NoMatch,
}

/// The full dry-run report — one [`PlannedAction`] per .pdf in the
/// scanned folder. Generated by [`plan_backfill`], consumed by
/// [`execute_backfill`] (or discarded if the user clicks Cancel).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillReport {
    /// Absolute path to the folder that was scanned.
    pub folder: String,
    /// Total .pdf files discovered (== `planned.len()`).
    pub scanned: usize,
    /// Per-file plan, in directory-walk order (stable across runs on
    /// the same filesystem because we sort by name before returning).
    pub planned: Vec<PlannedAction>,
    /// Unix-seconds timestamp the report was produced. The UI shows a
    /// "stale plan, re-scan?" hint if the user delays more than ~60s
    /// between planning and applying.
    pub generated_at: u64,
}

/// Per-file outcome of `execute_backfill` — sibling to [`PlannedAction`]
/// but reports *what actually happened* rather than what was planned.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillOutcome {
    pub source_path: String,
    pub destination: Option<String>,
    pub status: OutcomeStatus,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum OutcomeStatus {
    Moved,
    Skipped,
    Failed,
}

/// Aggregate summary returned by `execute_backfill` — the UI shows this
/// in a toast and `store::record_backfill_run` persists it for the
/// "Recent backfills" panel.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillRun {
    pub folder: String,
    pub scanned: usize,
    pub applied: usize,
    pub skipped: usize,
    pub errored: usize,
    pub started_at: u64,
    pub finished_at: u64,
    pub per_file: Vec<BackfillOutcome>,
}

// ─── Public API ───────────────────────────────────────────────────────

/// Walk `folder` non-recursively, evaluate each `*.pdf` against the
/// rule chain, return a [`BackfillReport`]. **Pure function** — never
/// touches anything outside `folder` (read-only there too).
///
/// `base_watch.output_dir` and `base_watch.rename_pattern` form the
/// fallback when no rule matches. Hidden files (starting with `.`) are
/// skipped silently — they're rarely user PDFs and including them
/// surfs into macOS Spotlight noise.
pub fn plan_backfill(folder: &Path, base_watch: &Watch, rules: &[Rule]) -> BackfillReport {
    let now = unix_now();
    let folder_str = folder.display().to_string();

    let mut planned: Vec<PlannedAction> = Vec::new();

    // Single-level scan — recursive is a future option (the UI will
    // surface a "include sub-folders" checkbox in a follow-up tick).
    let read_dir = match fs::read_dir(folder) {
        Ok(r) => r,
        Err(e) => {
            // Whole folder unreadable — emit a single Skip row so the
            // UI has something to render instead of an empty table.
            planned.push(PlannedAction {
                source_path: folder_str.clone(),
                size_bytes: 0,
                matched_rule: None,
                destination: None,
                action: ActionKind::Skip,
                reason: format!("could not read folder: {e}"),
            });
            return BackfillReport {
                folder: folder_str,
                scanned: 0,
                planned,
                generated_at: now,
            };
        }
    };

    // Collect first so we can sort by filename — deterministic plans
    // help the UI's "did this change?" diff and let the test suite
    // assert order without flaking on inode iteration.
    let mut entries: Vec<PathBuf> = read_dir
        .filter_map(|e| e.ok().map(|d| d.path()))
        .filter(|p| {
            // PDFs only, non-hidden, files only.
            if !p.is_file() {
                return false;
            }
            let Some(name) = p.file_name().and_then(|n| n.to_str()) else {
                return false;
            };
            if name.starts_with('.') {
                return false;
            }
            p.extension()
                .and_then(|e| e.to_str())
                .map(|e| e.eq_ignore_ascii_case("pdf"))
                .unwrap_or(false)
        })
        .collect();
    entries.sort();

    for path in entries {
        planned.push(plan_one(&path, base_watch, rules));
    }

    let scanned = planned.len();
    BackfillReport {
        folder: folder_str,
        scanned,
        planned,
        generated_at: now,
    }
}

/// Commit a previously-generated [`BackfillReport`]. Idempotent:
///
/// - Source file vanished between plan and apply → `Skipped` (not error).
/// - Destination already exists at the exact target path → the move
///   is disambiguated to ` (1).pdf`, ` (2).pdf`, …
/// - Cross-device rename falls back to copy + remove (same pattern the
///   live pipeline uses).
///
/// Re-running with the same report twice is safe — the second run will
/// emit `Skipped` for everything because the sources are gone.
pub fn execute_backfill(report: &BackfillReport) -> BackfillRun {
    let started = unix_now();
    let mut per_file = Vec::with_capacity(report.planned.len());
    let mut applied = 0usize;
    let mut skipped = 0usize;
    let mut errored = 0usize;

    for plan in &report.planned {
        let outcome = apply_one(plan);
        match outcome.status {
            OutcomeStatus::Moved => applied += 1,
            OutcomeStatus::Skipped => skipped += 1,
            OutcomeStatus::Failed => errored += 1,
        }
        per_file.push(outcome);
    }

    BackfillRun {
        folder: report.folder.clone(),
        scanned: report.scanned,
        applied,
        skipped,
        errored,
        started_at: started,
        finished_at: unix_now(),
        per_file,
    }
}

// ─── Internals ────────────────────────────────────────────────────────

fn plan_one(path: &Path, base_watch: &Watch, rules: &[Rule]) -> PlannedAction {
    let source = path.display().to_string();

    let meta = match fs::metadata(path) {
        Ok(m) => m,
        Err(e) => {
            return PlannedAction {
                source_path: source,
                size_bytes: 0,
                matched_rule: None,
                destination: None,
                action: ActionKind::Skip,
                reason: format!("metadata failed: {e}"),
            };
        }
    };

    let filename = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    let parent_dir = path.parent().and_then(|p| p.to_str()).unwrap_or("");
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("document")
        .to_string();
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("pdf")
        .to_lowercase();

    let ctx = RuleContext {
        filename,
        parent_dir,
        size_bytes: meta.len(),
        // v1 backfill keeps it cheap — no per-file text extraction or
        // page-count probe. Predicates that need those simply won't
        // match, which is the same fall-through behaviour as the live
        // watcher today.
        page_count: None,
        text_sample: None,
    };
    let resolved = evaluate_rules(rules, base_watch, &ctx);

    // Apply the rename template (date / stem only — AI title is not
    // available without async Beacon, see module docs).
    let date = today_iso8601();
    let final_name = match resolved.rename_pattern.as_deref() {
        Some(pattern) => super::rename::apply_pattern(pattern, &date, None, &stem, &ext),
        None => format!("{}.{ext}", super::rename::slugify(&stem)),
    };

    let dest = PathBuf::from(&resolved.output_dir).join(&final_name);
    let reason = match &resolved.matched_rule {
        Some(name) => format!("matched rule '{name}'"),
        None => "watch defaults (no rule matched)".to_string(),
    };

    PlannedAction {
        source_path: source,
        size_bytes: meta.len(),
        matched_rule: resolved.matched_rule,
        destination: Some(dest.display().to_string()),
        action: ActionKind::Move,
        reason,
    }
}

fn apply_one(plan: &PlannedAction) -> BackfillOutcome {
    let src = PathBuf::from(&plan.source_path);

    // Plan-time skip (e.g. metadata failed) → carry through.
    if matches!(plan.action, ActionKind::Skip | ActionKind::NoMatch) {
        return BackfillOutcome {
            source_path: plan.source_path.clone(),
            destination: None,
            status: OutcomeStatus::Skipped,
            error: Some(plan.reason.clone()),
        };
    }

    if !src.exists() {
        return BackfillOutcome {
            source_path: plan.source_path.clone(),
            destination: None,
            status: OutcomeStatus::Skipped,
            error: Some("source vanished between plan and apply".into()),
        };
    }

    let Some(dest_str) = plan.destination.as_ref() else {
        return BackfillOutcome {
            source_path: plan.source_path.clone(),
            destination: None,
            status: OutcomeStatus::Failed,
            error: Some("plan has no destination".into()),
        };
    };

    let dest = PathBuf::from(dest_str);
    if let Some(parent) = dest.parent() {
        if let Err(e) = fs::create_dir_all(parent) {
            return BackfillOutcome {
                source_path: plan.source_path.clone(),
                destination: Some(dest_str.clone()),
                status: OutcomeStatus::Failed,
                error: Some(format!("mkdir destination: {e}")),
            };
        }
    }

    // Disambiguate against existing files at the exact target path.
    let final_dest = unique_path(dest);

    // Try fs::rename first (cheap, same-FS); fall back to copy + remove
    // for cross-device moves (same strategy as the live pipeline).
    if let Err(rename_err) = fs::rename(&src, &final_dest) {
        match fs::copy(&src, &final_dest).and_then(|_| fs::remove_file(&src)) {
            Ok(_) => {}
            Err(copy_err) => {
                return BackfillOutcome {
                    source_path: plan.source_path.clone(),
                    destination: Some(final_dest.display().to_string()),
                    status: OutcomeStatus::Failed,
                    error: Some(format!(
                        "rename failed ({rename_err}); copy fallback failed: {copy_err}"
                    )),
                };
            }
        }
    }

    BackfillOutcome {
        source_path: plan.source_path.clone(),
        destination: Some(final_dest.display().to_string()),
        status: OutcomeStatus::Moved,
        error: None,
    }
}

fn unique_path(candidate: PathBuf) -> PathBuf {
    if !candidate.exists() {
        return candidate;
    }
    let parent = candidate.parent().unwrap_or_else(|| Path::new("."));
    let stem = candidate
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("file")
        .to_string();
    let ext = candidate.extension().and_then(|s| s.to_str()).unwrap_or("");
    for i in 1..=999 {
        let name = if ext.is_empty() {
            format!("{stem} ({i})")
        } else {
            format!("{stem} ({i}).{ext}")
        };
        let cand = parent.join(name);
        if !cand.exists() {
            return cand;
        }
    }
    candidate
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn today_iso8601() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as i64;
    let days = secs.div_euclid(86_400);
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = (z - era * 146_097) as u32;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i32 + era as i32 * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = y + if m <= 2 { 1 } else { 0 };
    format!("{y:04}-{m:02}-{d:02}")
}

// ─── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pdf::hopper::rules::{Rule, RuleAction, RulePredicate};
    use std::fs::{create_dir_all, write};

    fn base_watch(out: &Path) -> Watch {
        Watch {
            id: 42,
            source_dir: "/in".into(),
            output_dir: out.display().to_string(),
            recipe_id: None,
            rename_pattern: None,
            ai_rename: false,
            enabled: true,
            created_at: "0".into(),
        }
    }

    fn seed_pdfs(dir: &Path, names: &[&str]) {
        for n in names {
            write(dir.join(n), b"%PDF-1.4\n").unwrap();
        }
    }

    // ─── Type round-trip ────────────────────────────────────────────

    #[test]
    fn planned_action_round_trips_through_json() {
        let p = PlannedAction {
            source_path: "/in/a.pdf".into(),
            size_bytes: 100,
            matched_rule: Some("tax".into()),
            destination: Some("/out/a.pdf".into()),
            action: ActionKind::Move,
            reason: "matched rule 'tax'".into(),
        };
        let j = serde_json::to_string(&p).unwrap();
        let back: PlannedAction = serde_json::from_str(&j).unwrap();
        assert_eq!(p, back);
        assert!(j.contains("\"action\":\"move\""));
    }

    #[test]
    fn action_kind_serde_kebab_case() {
        for (k, expected) in [
            (ActionKind::Move, "\"move\""),
            (ActionKind::Copy, "\"copy\""),
            (ActionKind::Skip, "\"skip\""),
            (ActionKind::NoMatch, "\"no-match\""),
        ] {
            assert_eq!(serde_json::to_string(&k).unwrap(), expected);
        }
    }

    #[test]
    fn outcome_status_serde_lowercase() {
        assert_eq!(
            serde_json::to_string(&OutcomeStatus::Moved).unwrap(),
            "\"moved\""
        );
    }

    // ─── plan_backfill ──────────────────────────────────────────────

    #[test]
    fn plan_backfill_empty_folder_returns_zero_scanned() {
        let dir = tempfile::tempdir().unwrap();
        let report = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        assert_eq!(report.scanned, 0);
        assert!(report.planned.is_empty());
    }

    #[test]
    fn plan_backfill_only_picks_up_pdfs() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["a.pdf", "b.PDF", "c.pdf"]);
        write(dir.path().join("notes.txt"), b"hi").unwrap();
        write(dir.path().join(".hidden.pdf"), b"%PDF").unwrap();
        create_dir_all(dir.path().join("sub")).unwrap();

        let report = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        assert_eq!(
            report.scanned, 3,
            "expected 3 PDFs, got {:?}",
            report.planned
        );
        let names: Vec<_> = report
            .planned
            .iter()
            .map(|p| {
                Path::new(&p.source_path)
                    .file_name()
                    .unwrap()
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        assert_eq!(names, vec!["a.pdf", "b.PDF", "c.pdf"]);
    }

    #[test]
    fn plan_backfill_applies_first_matching_rule() {
        let src = tempfile::tempdir().unwrap();
        let out_default = tempfile::tempdir().unwrap();
        let out_tax = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["tax_2026.pdf", "invoice.pdf"]);

        let rules = vec![Rule {
            name: "Tax docs".into(),
            predicate: RulePredicate::FilenameGlob {
                pattern: "tax_*.pdf".into(),
            },
            action: RuleAction {
                recipe_id: None,
                output_dir: Some(out_tax.path().display().to_string()),
                rename_pattern: None,
            },
        }];
        let report = plan_backfill(src.path(), &base_watch(out_default.path()), &rules);

        assert_eq!(report.scanned, 2);
        let tax = report
            .planned
            .iter()
            .find(|p| p.source_path.ends_with("tax_2026.pdf"))
            .unwrap();
        assert_eq!(tax.matched_rule.as_deref(), Some("Tax docs"));
        assert!(
            tax.destination
                .as_ref()
                .unwrap()
                .starts_with(&out_tax.path().display().to_string()),
            "tax → tax output, got {:?}",
            tax.destination
        );

        let inv = report
            .planned
            .iter()
            .find(|p| p.source_path.ends_with("invoice.pdf"))
            .unwrap();
        assert!(inv.matched_rule.is_none());
        assert!(
            inv.destination
                .as_ref()
                .unwrap()
                .starts_with(&out_default.path().display().to_string()),
            "non-matching → watch default"
        );
    }

    #[test]
    fn plan_backfill_unreadable_folder_returns_single_skip() {
        let missing = Path::new("/definitely/does/not/exist/cake");
        let report = plan_backfill(missing, &base_watch(Path::new("/tmp/out")), &[]);
        assert_eq!(report.scanned, 0);
        assert_eq!(report.planned.len(), 1);
        assert!(matches!(report.planned[0].action, ActionKind::Skip));
    }

    #[test]
    fn plan_backfill_planned_actions_are_alphabetically_stable() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["zebra.pdf", "alpha.pdf", "mango.pdf"]);
        let r1 = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        let r2 = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        let names1: Vec<_> = r1.planned.iter().map(|p| p.source_path.clone()).collect();
        let names2: Vec<_> = r2.planned.iter().map(|p| p.source_path.clone()).collect();
        assert_eq!(names1, names2);
        assert!(names1[0].ends_with("alpha.pdf"));
        assert!(names1[2].ends_with("zebra.pdf"));
    }

    // ─── execute_backfill ───────────────────────────────────────────

    #[test]
    fn execute_backfill_moves_files_and_reports_outcomes() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["one.pdf", "two.pdf"]);

        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        assert_eq!(report.scanned, 2);
        let run = execute_backfill(&report);

        assert_eq!(run.applied, 2, "{:?}", run.per_file);
        assert_eq!(run.skipped, 0);
        assert_eq!(run.errored, 0);
        // Originals gone …
        assert!(!src.path().join("one.pdf").exists());
        assert!(!src.path().join("two.pdf").exists());
        // … and reachable in the destination.
        let out_files: Vec<_> = fs::read_dir(out.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        assert_eq!(out_files.len(), 2);
    }

    #[test]
    fn execute_backfill_is_idempotent_on_missing_source() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["solo.pdf"]);
        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        let _first = execute_backfill(&report);
        // Re-run against the same report — sources are gone.
        let second = execute_backfill(&report);
        assert_eq!(second.applied, 0);
        assert_eq!(second.skipped, 1);
        assert!(second.per_file[0]
            .error
            .as_deref()
            .unwrap()
            .contains("vanished"));
    }

    #[test]
    fn execute_backfill_disambiguates_destination_collisions() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["collide.pdf"]);
        // Pre-seed a file at the would-be destination.
        write(out.path().join("collide.pdf"), b"existing").unwrap();

        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        let run = execute_backfill(&report);
        assert_eq!(run.applied, 1);
        // Disambiguated filename — original survives, new one renamed.
        let names: Vec<_> = fs::read_dir(out.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        assert!(names.contains(&"collide.pdf".to_string()));
        assert!(names.iter().any(|n| n.contains("(1)")));
    }

    #[test]
    fn execute_backfill_skip_action_passes_through() {
        let report = BackfillReport {
            folder: "/x".into(),
            scanned: 1,
            generated_at: 0,
            planned: vec![PlannedAction {
                source_path: "/no/such/file.pdf".into(),
                size_bytes: 0,
                matched_rule: None,
                destination: None,
                action: ActionKind::Skip,
                reason: "probe failed".into(),
            }],
        };
        let run = execute_backfill(&report);
        assert_eq!(run.applied, 0);
        assert_eq!(run.skipped, 1);
        assert_eq!(run.errored, 0);
    }

    #[test]
    fn backfill_run_round_trips_through_json() {
        let r = BackfillRun {
            folder: "/in".into(),
            scanned: 3,
            applied: 2,
            skipped: 1,
            errored: 0,
            started_at: 100,
            finished_at: 200,
            per_file: vec![],
        };
        let j = serde_json::to_string(&r).unwrap();
        let back: BackfillRun = serde_json::from_str(&j).unwrap();
        assert_eq!(r, back);
    }
}
