//! Hopper backfill — apply current rules to PDFs already sitting in a
//! watched folder (v3.22.0 "Hopper Loop").
//!
//! v3.20 shipped folder watching. v3.21 shipped per-folder rules. This
//! module closes the loop with **batch backfill**: when a user finishes
//! editing a rule list they almost always have hundreds of legacy PDFs
//! already in the folder that the live watcher never saw. Backfill
//! evaluates those files against the current rule chain and reports
//! exactly what would happen — file by file — *before* committing any
//! filesystem move. The UI ("Test on this folder…") renders the
//! [`BackfillReport`] as a table; the user clicks Apply and we call
//! [`execute_backfill`] to actually perform the moves idempotently.
//!
//! ## Why this exists
//!
//! - Paralegals routinely have a 2,000-PDF discovery folder that needs
//!   to be sliced into per-matter sub-folders. Adobe Acrobat has no
//!   equivalent — every batch action is per-file dialog hell.
//! - Hazel ($42) can do generic moves but is mac-only and has no
//!   PDF-aware predicates (page count, text contains).
//! - Slab's wedge: enterprise-grade local PDF automation, zero cloud.
//!
//! ## Buy-button test
//!
//! - **Pick-us**: "drop 4,000 PDFs in inbox, get routed by my rules in
//!   30 seconds" — Acrobat literally cannot.
//! - **Tell-a-friend**: the dry-run preview table itself is a wow.
//!
//! ## Module layout
//!
//! - [`plan_backfill`] — pure-fn walk + rule evaluation, no FS mutation.
//! - [`execute_backfill`] — commit a previously-planned report.
//! - [`BackfillReport`] / [`PlannedAction`] / [`BackfillRun`] — typed
//!   results that the UI renders directly.

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use super::registry::Watch;
use super::rules::{evaluate_rules, Rule, RuleContext};

// ─── Types ────────────────────────────────────────────────────────────

/// What `plan_backfill` decided would happen to a single file. The UI
/// renders one of these per table row; the user can deselect any row
/// before clicking Apply.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PlannedAction {
    /// Absolute path to the source file the planner inspected.
    pub source_path: String,
    /// Display-only file size in bytes (lets the table sort by size).
    pub size_bytes: u64,
    /// Name of the rule that matched, if any. `None` means the watch
    /// defaults applied (still routes — the action will be `Move`).
    pub matched_rule: Option<String>,
    /// Where the file would land if `execute_backfill` runs on this
    /// report. `None` only for `Skip` actions (e.g. probe error).
    pub destination: Option<String>,
    /// What [`execute_backfill`] will do with this entry.
    pub action: ActionKind,
    /// Human-readable explanation — shown in the UI tooltip and used
    /// in the JSON report for audit trails. Always populated.
    pub reason: String,
}

/// Discriminator for [`PlannedAction::action`]. `kebab-case` on the
/// wire to match the rest of the Hopper TS shapes.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum ActionKind {
    /// File will be moved to `destination` (recipe applied first if the
    /// resolved routing has one — but v1 backfill is **rename + move
    /// only**, no recipe execution, see module docs).
    Move,
    /// Reserved for a future "preserve original, write copy" mode. Not
    /// emitted by v3.22 but the variant is part of the wire contract so
    /// the UI is forward-compatible.
    Copy,
    /// Skipped at plan time — probe error, unreadable file, etc. The
    /// `reason` field explains why; this row will be greyed out in the UI.
    Skip,
    /// No rule matched **and** the watch has no default `output_dir`
    /// (impossible today — `output_dir` is required — but variant kept
    /// for forward-compat with optional output_dir watches).
    NoMatch,
}

/// The full dry-run report — one [`PlannedAction`] per .pdf in the
/// scanned folder. Generated by [`plan_backfill`], consumed by
/// [`execute_backfill`] (or discarded if the user clicks Cancel).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillReport {
    /// Absolute path to the folder that was scanned.
    pub folder: String,
    /// Total .pdf files discovered (== `planned.len()`).
    pub scanned: usize,
    /// Per-file plan, in directory-walk order (stable across runs on
    /// the same filesystem because we sort by name before returning).
    pub planned: Vec<PlannedAction>,
    /// Unix-seconds timestamp the report was produced. The UI shows a
    /// "stale plan, re-scan?" hint if the user delays more than ~60s
    /// between planning and applying.
    pub generated_at: u64,
}

/// Per-file outcome of `execute_backfill` — sibling to [`PlannedAction`]
/// but reports *what actually happened* rather than what was planned.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillOutcome {
    pub source_path: String,
    pub destination: Option<String>,
    pub status: OutcomeStatus,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum OutcomeStatus {
    Moved,
    Skipped,
    Failed,
}

/// Aggregate summary returned by `execute_backfill` — the UI shows this
/// in a toast and `store::record_backfill_run` persists it for the
/// "Recent backfills" panel.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillRun {
    pub folder: String,
    pub scanned: usize,
    pub applied: usize,
    pub skipped: usize,
    pub errored: usize,
    pub started_at: u64,
    pub finished_at: u64,
    pub per_file: Vec<BackfillOutcome>,
}

// ─── Public API ───────────────────────────────────────────────────────

/// Tunables for [`plan_backfill_with_options`]. Default values match
/// the original v3.22 [`plan_backfill`] behaviour (single-level scan)
/// so widening the contract is fully back-compat.
///
/// `recursive = true` is the v3.39 round-10 follow-on: paralegals
/// routinely have a discovery dump shaped like `discovery/2024-Q1/`,
/// `discovery/2024-Q2/`, … and they want to point Hopper at
/// `discovery/` once and have every sub-folder swept. Hazel can't do
/// PDF-aware predicates *and* recurse; Acrobat batch actions can't
/// recurse at all.
///
/// `max_depth = None` means "no cap, walk forever". `Some(n)` caps the
/// recursion at `n` levels below `folder` (0 = same as
/// non-recursive — the root is "depth 0"). The UI surfaces depth-1 or
/// depth-3 caps as guardrails for users who fat-finger their root.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct PlanOptions {
    /// Walk sub-folders too. Default `false` preserves single-level
    /// semantics. When `true`, hidden directories (starting with `.`)
    /// are still skipped — same hostility-to-Spotlight-noise rule that
    /// already applies to hidden files.
    pub recursive: bool,
    /// Cap on recursion depth — `None` for unbounded, `Some(0)` matches
    /// `recursive = false` exactly. Ignored when `recursive = false`.
    pub max_depth: Option<u32>,
}

/// Back-compat wrapper for [`plan_backfill_with_options`] using the
/// default (non-recursive) `PlanOptions`. Every pre-v3.39 caller stays
/// behaviourally identical — no UI changes required to adopt the
/// widened module.
pub fn plan_backfill(folder: &Path, base_watch: &Watch, rules: &[Rule]) -> BackfillReport {
    plan_backfill_with_options(folder, base_watch, rules, &PlanOptions::default())
}

/// Walk `folder` (optionally recursive per `opts`), evaluate each
/// `*.pdf` against the rule chain, return a [`BackfillReport`]. **Pure
/// function** — never touches anything outside `folder` (read-only
/// there too).
///
/// `base_watch.output_dir` and `base_watch.rename_pattern` form the
/// fallback when no rule matches. Hidden files (starting with `.`) and
/// hidden directories are skipped silently — they're rarely user PDFs
/// and including them surfs into macOS Spotlight noise.
///
/// Plan order is deterministic across runs on the same filesystem
/// (collected, then sorted alphabetically by full path) so the UI's
/// "did this plan change?" diff is stable and tests can assert order.
pub fn plan_backfill_with_options(
    folder: &Path,
    base_watch: &Watch,
    rules: &[Rule],
    opts: &PlanOptions,
) -> BackfillReport {
    let now = unix_now();
    let folder_str = folder.display().to_string();

    let mut planned: Vec<PlannedAction> = Vec::new();
    let mut pdf_paths: Vec<PathBuf> = Vec::new();

    // Treat `folder` as depth-0; recurse via a small explicit stack so
    // we keep the stable, predictable iteration order without paying
    // for an extra crate (walkdir would pull in a transitive dep just
    // for this single call site).
    let max_depth = if opts.recursive {
        opts.max_depth.unwrap_or(u32::MAX)
    } else {
        0
    };

    if let Err(e) = collect_pdfs(folder, 0, max_depth, &mut pdf_paths) {
        // Whole folder unreadable — emit a single Skip row so the UI
        // has something to render instead of an empty table.
        planned.push(PlannedAction {
            source_path: folder_str.clone(),
            size_bytes: 0,
            matched_rule: None,
            destination: None,
            action: ActionKind::Skip,
            reason: format!("could not read folder: {e}"),
        });
        return BackfillReport {
            folder: folder_str,
            scanned: 0,
            planned,
            generated_at: now,
        };
    }

    // Deterministic order — sort the full set after the walk completes
    // so the report is the same regardless of inode iteration quirks.
    pdf_paths.sort();

    for path in pdf_paths {
        planned.push(plan_one(&path, base_watch, rules));
    }

    let scanned = planned.len();
    BackfillReport {
        folder: folder_str,
        scanned,
        planned,
        generated_at: now,
    }
}

/// Walk `folder` and push every `*.pdf` into `out`. `current_depth`
/// counts levels below the original root; `max_depth` is the inclusive
/// cap (== 0 → root only, == u32::MAX → unbounded). Hidden entries
/// (files or dirs starting with `.`) are skipped silently.
///
/// Returns `Err` only if the root `folder` itself can't be read —
/// individual sub-folders that fail are skipped silently (a permission-
/// denied sub-folder shouldn't kill the whole backfill plan).
fn collect_pdfs(
    folder: &Path,
    current_depth: u32,
    max_depth: u32,
    out: &mut Vec<PathBuf>,
) -> std::io::Result<()> {
    let read_dir = fs::read_dir(folder)?;
    for entry in read_dir.flatten() {
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name.starts_with('.') {
            continue;
        }
        if path.is_file() {
            let is_pdf = path
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e.eq_ignore_ascii_case("pdf"))
                .unwrap_or(false);
            if is_pdf {
                out.push(path);
            }
        } else if path.is_dir() && current_depth < max_depth {
            // Sub-folder read errors are swallowed: a single locked
            // sub-folder shouldn't blow up the whole report. The UI
            // can still flag missing files later via per-file reasons.
            let _ = collect_pdfs(&path, current_depth + 1, max_depth, out);
        }
    }
    Ok(())
}

/// Commit a previously-generated [`BackfillReport`]. Idempotent:
///
/// - Source file vanished between plan and apply → `Skipped` (not error).
/// - Destination already exists at the exact target path → the move
///   is disambiguated to ` (1).pdf`, ` (2).pdf`, …
/// - Cross-device rename falls back to copy + remove (same pattern the
///   live pipeline uses).
///
/// Re-running with the same report twice is safe — the second run will
/// emit `Skipped` for everything because the sources are gone.
pub fn execute_backfill(report: &BackfillReport) -> BackfillRun {
    // Delegate to the streaming variant with a no-op progress sink +
    // an always-armed CancelFlag that's never tripped. Keeps the two
    // entry points behaviour-identical so a regression in
    // execute_backfill_streaming surfaces here too.
    execute_backfill_streaming(report, &CancelFlag::new(), |_| {})
}

/// Per-file progress event emitted by [`execute_backfill_streaming`]
/// after each file is processed. The Tauri command bridge converts
/// these into `hopper://backfill-progress` events the UI consumes for
/// live progress bars, scrolling tail, and Cancel button enablement.
///
/// Field order mirrors what the UI displays so a JSON dump is easy to
/// eyeball during debugging.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillProgress {
    /// 1-indexed position of the file just finished (`processed == total`
    /// signals \"loop complete\"). 0 only if the report is empty — the
    /// streaming fn still emits one tail-end frame with processed=0 so
    /// the UI can transition out of \"applying\" state cleanly.
    pub processed: usize,
    /// Total file count from `report.planned.len()` — constant for the
    /// duration of one run. Snapshot so the UI doesn't need to read it
    /// out of `report` every frame.
    pub total: usize,
    /// Running tallies updated *after* this file's outcome is recorded.
    pub applied: usize,
    pub skipped: usize,
    pub errored: usize,
    /// The outcome the loop just produced — `None` only on the final
    /// \"loop complete\" frame for an empty report (no file was
    /// processed). Lets the UI append to a scrolling tail without
    /// having to diff the full per_file vector.
    pub current: Option<BackfillOutcome>,
}

/// Tauri-event payload — the wire envelope the `tauri::AppHandle`
/// `RunEmitter` impl publishes on `hopper://backfill-progress`. The
/// `run_id` lets the frontend route events to the right component
/// instance when multiple backfills are in flight (today the UI gates
/// to one at a time, but the wire contract scales).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BackfillProgressEvent {
    pub run_id: i64,
    pub progress: BackfillProgress,
}

/// Atomic flag the Tauri layer flips to ask
/// [`execute_backfill_streaming`] to short-circuit the remaining
/// files. Checked *before* each apply — once tripped, every remaining
/// file emits `OutcomeStatus::Skipped` with the canned
/// [`CANCELLED_REASON`] so the user sees explicit cancel feedback.
///
/// Cheap to clone (Arc inside) — the service registers one per
/// in-flight run keyed by run_id so cancel commands can find it.
#[derive(Clone, Debug, Default)]
pub struct CancelFlag {
    inner: Arc<AtomicBool>,
}

/// Reason string stamped onto rows skipped because the user clicked
/// Cancel. Kept as a module constant so tests can pin the exact text
/// and the UI can highlight cancelled rows in a dimmed style.
pub const CANCELLED_REASON: &str = "cancelled by user";

impl CancelFlag {
    /// Construct a fresh flag in the \"not cancelled\" state.
    pub fn new() -> Self {
        Self::default()
    }

    /// Flip the flag — subsequent
    /// [`execute_backfill_streaming`] iterations short-circuit. Safe
    /// to call from any thread; multiple calls are idempotent.
    pub fn cancel(&self) {
        self.inner.store(true, Ordering::SeqCst);
    }

    /// Read the current flag value. Pure read, no side effect.
    pub fn is_cancelled(&self) -> bool {
        self.inner.load(Ordering::SeqCst)
    }
}

/// Streaming variant of [`execute_backfill`] — same semantics, but
/// invokes `on_progress` after every file with a [`BackfillProgress`]
/// snapshot so the UI can render a live progress bar + scrolling
/// outcome tail.
///
/// Honours `cancel`:
///
/// - Checked *before* each apply; once tripped, the remaining files
///   emit `OutcomeStatus::Skipped` with [`CANCELLED_REASON`].
/// - Progress callbacks fire for every file including the cancelled
///   tail (so the UI can keep its progress bar moving and let the
///   user watch the loop wind down cleanly).
/// - A trailing `processed = total` frame always fires once the loop
///   exits — including for empty reports, where it carries
///   `processed = 0, current = None` so the UI can transition out of
///   \"applying\" state in exactly one place.
///
/// `on_progress` is a `FnMut` (not `Fn`) so the Tauri caller can
/// mutate per-frame buffers without an interior-mutability dance.
pub fn execute_backfill_streaming(
    report: &BackfillReport,
    cancel: &CancelFlag,
    mut on_progress: impl FnMut(&BackfillProgress),
) -> BackfillRun {
    let started = unix_now();
    let total = report.planned.len();
    let mut per_file: Vec<BackfillOutcome> = Vec::with_capacity(total);
    let mut applied = 0usize;
    let mut skipped = 0usize;
    let mut errored = 0usize;

    for (i, plan) in report.planned.iter().enumerate() {
        let outcome = if cancel.is_cancelled() {
            BackfillOutcome {
                source_path: plan.source_path.clone(),
                destination: None,
                status: OutcomeStatus::Skipped,
                error: Some(CANCELLED_REASON.to_string()),
            }
        } else {
            apply_one(plan)
        };

        match outcome.status {
            OutcomeStatus::Moved => applied += 1,
            OutcomeStatus::Skipped => skipped += 1,
            OutcomeStatus::Failed => errored += 1,
        }
        per_file.push(outcome.clone());

        on_progress(&BackfillProgress {
            processed: i + 1,
            total,
            applied,
            skipped,
            errored,
            current: Some(outcome),
        });
    }

    // Always emit a final \"loop complete\" frame for an empty report
    // so the UI has exactly one transition point out of \"applying\".
    // For non-empty reports the last per-file frame already has
    // processed == total, so this is a no-op.
    if total == 0 {
        on_progress(&BackfillProgress {
            processed: 0,
            total: 0,
            applied: 0,
            skipped: 0,
            errored: 0,
            current: None,
        });
    }

    BackfillRun {
        folder: report.folder.clone(),
        scanned: report.scanned,
        applied,
        skipped,
        errored,
        started_at: started,
        finished_at: unix_now(),
        per_file,
    }
}

// ─── Internals ────────────────────────────────────────────────────────

fn plan_one(path: &Path, base_watch: &Watch, rules: &[Rule]) -> PlannedAction {
    let source = path.display().to_string();

    let meta = match fs::metadata(path) {
        Ok(m) => m,
        Err(e) => {
            return PlannedAction {
                source_path: source,
                size_bytes: 0,
                matched_rule: None,
                destination: None,
                action: ActionKind::Skip,
                reason: format!("metadata failed: {e}"),
            };
        }
    };

    let filename = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    let parent_dir = path.parent().and_then(|p| p.to_str()).unwrap_or("");
    let stem = path
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("document")
        .to_string();
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("pdf")
        .to_lowercase();

    let ctx = RuleContext {
        filename,
        parent_dir,
        size_bytes: meta.len(),
        // v1 backfill keeps it cheap — no per-file text extraction or
        // page-count probe. Predicates that need those simply won't
        // match, which is the same fall-through behaviour as the live
        // watcher today.
        page_count: None,
        text_sample: None,
    };
    let resolved = evaluate_rules(rules, base_watch, &ctx);

    // Apply the rename template (date / stem only — AI title is not
    // available without async Beacon, see module docs).
    let date = today_iso8601();
    let final_name = match resolved.rename_pattern.as_deref() {
        Some(pattern) => super::rename::apply_pattern(pattern, &date, None, &stem, &ext),
        None => format!("{}.{ext}", super::rename::slugify(&stem)),
    };

    let dest = PathBuf::from(&resolved.output_dir).join(&final_name);
    let reason = match &resolved.matched_rule {
        Some(name) => format!("matched rule '{name}'"),
        None => "watch defaults (no rule matched)".to_string(),
    };

    PlannedAction {
        source_path: source,
        size_bytes: meta.len(),
        matched_rule: resolved.matched_rule,
        destination: Some(dest.display().to_string()),
        action: ActionKind::Move,
        reason,
    }
}

fn apply_one(plan: &PlannedAction) -> BackfillOutcome {
    let src = PathBuf::from(&plan.source_path);

    // Plan-time skip (e.g. metadata failed) → carry through.
    if matches!(plan.action, ActionKind::Skip | ActionKind::NoMatch) {
        return BackfillOutcome {
            source_path: plan.source_path.clone(),
            destination: None,
            status: OutcomeStatus::Skipped,
            error: Some(plan.reason.clone()),
        };
    }

    if !src.exists() {
        return BackfillOutcome {
            source_path: plan.source_path.clone(),
            destination: None,
            status: OutcomeStatus::Skipped,
            error: Some("source vanished between plan and apply".into()),
        };
    }

    let Some(dest_str) = plan.destination.as_ref() else {
        return BackfillOutcome {
            source_path: plan.source_path.clone(),
            destination: None,
            status: OutcomeStatus::Failed,
            error: Some("plan has no destination".into()),
        };
    };

    let dest = PathBuf::from(dest_str);
    if let Some(parent) = dest.parent() {
        if let Err(e) = fs::create_dir_all(parent) {
            return BackfillOutcome {
                source_path: plan.source_path.clone(),
                destination: Some(dest_str.clone()),
                status: OutcomeStatus::Failed,
                error: Some(format!("mkdir destination: {e}")),
            };
        }
    }

    // Disambiguate against existing files at the exact target path.
    let final_dest = unique_path(dest);

    // Try fs::rename first (cheap, same-FS); fall back to copy + remove
    // for cross-device moves (same strategy as the live pipeline).
    if let Err(rename_err) = fs::rename(&src, &final_dest) {
        match fs::copy(&src, &final_dest).and_then(|_| fs::remove_file(&src)) {
            Ok(_) => {}
            Err(copy_err) => {
                return BackfillOutcome {
                    source_path: plan.source_path.clone(),
                    destination: Some(final_dest.display().to_string()),
                    status: OutcomeStatus::Failed,
                    error: Some(format!(
                        "rename failed ({rename_err}); copy fallback failed: {copy_err}"
                    )),
                };
            }
        }
    }

    BackfillOutcome {
        source_path: plan.source_path.clone(),
        destination: Some(final_dest.display().to_string()),
        status: OutcomeStatus::Moved,
        error: None,
    }
}

fn unique_path(candidate: PathBuf) -> PathBuf {
    if !candidate.exists() {
        return candidate;
    }
    let parent = candidate.parent().unwrap_or_else(|| Path::new("."));
    let stem = candidate
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("file")
        .to_string();
    let ext = candidate.extension().and_then(|s| s.to_str()).unwrap_or("");
    for i in 1..=999 {
        let name = if ext.is_empty() {
            format!("{stem} ({i})")
        } else {
            format!("{stem} ({i}).{ext}")
        };
        let cand = parent.join(name);
        if !cand.exists() {
            return cand;
        }
    }
    candidate
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn today_iso8601() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as i64;
    let days = secs.div_euclid(86_400);
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = (z - era * 146_097) as u32;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i32 + era as i32 * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = y + if m <= 2 { 1 } else { 0 };
    format!("{y:04}-{m:02}-{d:02}")
}

// ─── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pdf::hopper::rules::{Rule, RuleAction, RulePredicate};
    use std::fs::{create_dir_all, write};

    fn base_watch(out: &Path) -> Watch {
        Watch {
            id: 42,
            source_dir: "/in".into(),
            output_dir: out.display().to_string(),
            recipe_id: None,
            rename_pattern: None,
            ai_rename: false,
            enabled: true,
            created_at: "0".into(),
        }
    }

    fn seed_pdfs(dir: &Path, names: &[&str]) {
        for n in names {
            write(dir.join(n), b"%PDF-1.4\n").unwrap();
        }
    }

    // ─── Type round-trip ────────────────────────────────────────────

    #[test]
    fn planned_action_round_trips_through_json() {
        let p = PlannedAction {
            source_path: "/in/a.pdf".into(),
            size_bytes: 100,
            matched_rule: Some("tax".into()),
            destination: Some("/out/a.pdf".into()),
            action: ActionKind::Move,
            reason: "matched rule 'tax'".into(),
        };
        let j = serde_json::to_string(&p).unwrap();
        let back: PlannedAction = serde_json::from_str(&j).unwrap();
        assert_eq!(p, back);
        assert!(j.contains("\"action\":\"move\""));
    }

    #[test]
    fn action_kind_serde_kebab_case() {
        for (k, expected) in [
            (ActionKind::Move, "\"move\""),
            (ActionKind::Copy, "\"copy\""),
            (ActionKind::Skip, "\"skip\""),
            (ActionKind::NoMatch, "\"no-match\""),
        ] {
            assert_eq!(serde_json::to_string(&k).unwrap(), expected);
        }
    }

    #[test]
    fn outcome_status_serde_lowercase() {
        assert_eq!(
            serde_json::to_string(&OutcomeStatus::Moved).unwrap(),
            "\"moved\""
        );
    }

    // ─── plan_backfill ──────────────────────────────────────────────

    #[test]
    fn plan_backfill_empty_folder_returns_zero_scanned() {
        let dir = tempfile::tempdir().unwrap();
        let report = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        assert_eq!(report.scanned, 0);
        assert!(report.planned.is_empty());
    }

    #[test]
    fn plan_backfill_only_picks_up_pdfs() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["a.pdf", "b.PDF", "c.pdf"]);
        write(dir.path().join("notes.txt"), b"hi").unwrap();
        write(dir.path().join(".hidden.pdf"), b"%PDF").unwrap();
        create_dir_all(dir.path().join("sub")).unwrap();

        let report = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        assert_eq!(
            report.scanned, 3,
            "expected 3 PDFs, got {:?}",
            report.planned
        );
        let names: Vec<_> = report
            .planned
            .iter()
            .map(|p| {
                Path::new(&p.source_path)
                    .file_name()
                    .unwrap()
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        assert_eq!(names, vec!["a.pdf", "b.PDF", "c.pdf"]);
    }

    #[test]
    fn plan_backfill_applies_first_matching_rule() {
        let src = tempfile::tempdir().unwrap();
        let out_default = tempfile::tempdir().unwrap();
        let out_tax = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["tax_2026.pdf", "invoice.pdf"]);

        let rules = vec![Rule {
            name: "Tax docs".into(),
            predicate: RulePredicate::FilenameGlob {
                pattern: "tax_*.pdf".into(),
            },
            action: RuleAction {
                recipe_id: None,
                output_dir: Some(out_tax.path().display().to_string()),
                rename_pattern: None,
            },
        }];
        let report = plan_backfill(src.path(), &base_watch(out_default.path()), &rules);

        assert_eq!(report.scanned, 2);
        let tax = report
            .planned
            .iter()
            .find(|p| p.source_path.ends_with("tax_2026.pdf"))
            .unwrap();
        assert_eq!(tax.matched_rule.as_deref(), Some("Tax docs"));
        assert!(
            tax.destination
                .as_ref()
                .unwrap()
                .starts_with(&out_tax.path().display().to_string()),
            "tax → tax output, got {:?}",
            tax.destination
        );

        let inv = report
            .planned
            .iter()
            .find(|p| p.source_path.ends_with("invoice.pdf"))
            .unwrap();
        assert!(inv.matched_rule.is_none());
        assert!(
            inv.destination
                .as_ref()
                .unwrap()
                .starts_with(&out_default.path().display().to_string()),
            "non-matching → watch default"
        );
    }

    #[test]
    fn plan_backfill_unreadable_folder_returns_single_skip() {
        let missing = Path::new("/definitely/does/not/exist/cake");
        let report = plan_backfill(missing, &base_watch(Path::new("/tmp/out")), &[]);
        assert_eq!(report.scanned, 0);
        assert_eq!(report.planned.len(), 1);
        assert!(matches!(report.planned[0].action, ActionKind::Skip));
    }

    #[test]
    fn plan_backfill_planned_actions_are_alphabetically_stable() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["zebra.pdf", "alpha.pdf", "mango.pdf"]);
        let r1 = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        let r2 = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        let names1: Vec<_> = r1.planned.iter().map(|p| p.source_path.clone()).collect();
        let names2: Vec<_> = r2.planned.iter().map(|p| p.source_path.clone()).collect();
        assert_eq!(names1, names2);
        assert!(names1[0].ends_with("alpha.pdf"));
        assert!(names1[2].ends_with("zebra.pdf"));
    }

    // ─── plan_backfill_with_options (v3.39 round-10 recursive) ──────

    /// Default options must produce the EXACT same report as the legacy
    /// [`plan_backfill`]. Pins the back-compat promise so a future
    /// PlanOptions tweak can't quietly change pre-v3.39 behaviour.
    #[test]
    fn plan_options_default_matches_legacy_plan_backfill() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["a.pdf", "b.pdf"]);
        let legacy = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        let widened = plan_backfill_with_options(
            dir.path(),
            &base_watch(dir.path()),
            &[],
            &PlanOptions::default(),
        );
        // generated_at can differ by a second under bad luck; compare
        // everything else.
        assert_eq!(legacy.folder, widened.folder);
        assert_eq!(legacy.scanned, widened.scanned);
        assert_eq!(legacy.planned, widened.planned);
    }

    /// Recursive scan picks up PDFs in sub-folders; non-recursive does
    /// not. Pins the headline contract of the new option.
    #[test]
    fn plan_options_recursive_walks_subfolders() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["top.pdf"]);
        create_dir_all(dir.path().join("sub")).unwrap();
        seed_pdfs(&dir.path().join("sub"), &["nested.pdf"]);
        create_dir_all(dir.path().join("sub/inner")).unwrap();
        seed_pdfs(&dir.path().join("sub/inner"), &["deep.pdf"]);

        let flat = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        assert_eq!(flat.scanned, 1, "non-recursive sees only top.pdf");
        let recursive = plan_backfill_with_options(
            dir.path(),
            &base_watch(dir.path()),
            &[],
            &PlanOptions {
                recursive: true,
                max_depth: None,
            },
        );
        assert_eq!(recursive.scanned, 3, "recursive sees all 3 PDFs");
        let names: Vec<_> = recursive
            .planned
            .iter()
            .map(|p| {
                Path::new(&p.source_path)
                    .file_name()
                    .unwrap()
                    .to_string_lossy()
                    .to_string()
            })
            .collect();
        // Deterministic alphabetical-by-full-path order.
        assert!(names.contains(&"top.pdf".to_string()));
        assert!(names.contains(&"nested.pdf".to_string()));
        assert!(names.contains(&"deep.pdf".to_string()));
    }

    /// `max_depth = Some(1)` walks one level below the root but stops
    /// before deeper sub-trees. Validates the depth cap guardrail the
    /// UI surfaces for users who fat-finger their root.
    #[test]
    fn plan_options_max_depth_caps_recursion() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["root.pdf"]);
        create_dir_all(dir.path().join("L1")).unwrap();
        seed_pdfs(&dir.path().join("L1"), &["one.pdf"]);
        create_dir_all(dir.path().join("L1/L2")).unwrap();
        seed_pdfs(&dir.path().join("L1/L2"), &["two.pdf"]);

        let cap1 = plan_backfill_with_options(
            dir.path(),
            &base_watch(dir.path()),
            &[],
            &PlanOptions {
                recursive: true,
                max_depth: Some(1),
            },
        );
        assert_eq!(cap1.scanned, 2, "root + L1 only");

        let unbounded = plan_backfill_with_options(
            dir.path(),
            &base_watch(dir.path()),
            &[],
            &PlanOptions {
                recursive: true,
                max_depth: None,
            },
        );
        assert_eq!(unbounded.scanned, 3, "root + L1 + L2");
    }

    /// `max_depth = Some(0)` with `recursive = true` is functionally
    /// identical to `recursive = false`. Pins the edge case so a
    /// future refactor can't quietly drift.
    #[test]
    fn plan_options_max_depth_zero_matches_non_recursive() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["root.pdf"]);
        create_dir_all(dir.path().join("sub")).unwrap();
        seed_pdfs(&dir.path().join("sub"), &["nested.pdf"]);

        let rec_zero = plan_backfill_with_options(
            dir.path(),
            &base_watch(dir.path()),
            &[],
            &PlanOptions {
                recursive: true,
                max_depth: Some(0),
            },
        );
        let non_rec = plan_backfill(dir.path(), &base_watch(dir.path()), &[]);
        assert_eq!(rec_zero.scanned, 1);
        assert_eq!(rec_zero.scanned, non_rec.scanned);
    }

    /// Recursive walk still skips hidden sub-directories (matches the
    /// existing hidden-file rule). Spotlight noise stays out.
    #[test]
    fn plan_options_recursive_skips_hidden_subdirs() {
        let dir = tempfile::tempdir().unwrap();
        seed_pdfs(dir.path(), &["visible.pdf"]);
        create_dir_all(dir.path().join(".hidden_dir")).unwrap();
        seed_pdfs(&dir.path().join(".hidden_dir"), &["secret.pdf"]);

        let report = plan_backfill_with_options(
            dir.path(),
            &base_watch(dir.path()),
            &[],
            &PlanOptions {
                recursive: true,
                max_depth: None,
            },
        );
        assert_eq!(report.scanned, 1);
        assert!(report.planned[0].source_path.ends_with("visible.pdf"));
    }

    /// PlanOptions round-trips through serde — the Tauri command takes
    /// the shape directly from the frontend so a field rename here
    /// must surface in compilation.
    #[test]
    fn plan_options_round_trips_through_json() {
        let opts = PlanOptions {
            recursive: true,
            max_depth: Some(3),
        };
        let j = serde_json::to_string(&opts).unwrap();
        let back: PlanOptions = serde_json::from_str(&j).unwrap();
        assert_eq!(opts, back);
        // Default (false / None) also round-trips with serde defaults
        // so the field is optional on the wire.
        let default_back: PlanOptions = serde_json::from_str("{}").unwrap();
        assert_eq!(default_back, PlanOptions::default());
    }

    // ─── execute_backfill ───────────────────────────────────────────

    #[test]
    fn execute_backfill_moves_files_and_reports_outcomes() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["one.pdf", "two.pdf"]);

        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        assert_eq!(report.scanned, 2);
        let run = execute_backfill(&report);

        assert_eq!(run.applied, 2, "{:?}", run.per_file);
        assert_eq!(run.skipped, 0);
        assert_eq!(run.errored, 0);
        // Originals gone …
        assert!(!src.path().join("one.pdf").exists());
        assert!(!src.path().join("two.pdf").exists());
        // … and reachable in the destination.
        let out_files: Vec<_> = fs::read_dir(out.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        assert_eq!(out_files.len(), 2);
    }

    #[test]
    fn execute_backfill_is_idempotent_on_missing_source() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["solo.pdf"]);
        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        let _first = execute_backfill(&report);
        // Re-run against the same report — sources are gone.
        let second = execute_backfill(&report);
        assert_eq!(second.applied, 0);
        assert_eq!(second.skipped, 1);
        assert!(second.per_file[0]
            .error
            .as_deref()
            .unwrap()
            .contains("vanished"));
    }

    #[test]
    fn execute_backfill_disambiguates_destination_collisions() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["collide.pdf"]);
        // Pre-seed a file at the would-be destination.
        write(out.path().join("collide.pdf"), b"existing").unwrap();

        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        let run = execute_backfill(&report);
        assert_eq!(run.applied, 1);
        // Disambiguated filename — original survives, new one renamed.
        let names: Vec<_> = fs::read_dir(out.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
            .collect();
        assert!(names.contains(&"collide.pdf".to_string()));
        assert!(names.iter().any(|n| n.contains("(1)")));
    }

    #[test]
    fn execute_backfill_skip_action_passes_through() {
        let report = BackfillReport {
            folder: "/x".into(),
            scanned: 1,
            generated_at: 0,
            planned: vec![PlannedAction {
                source_path: "/no/such/file.pdf".into(),
                size_bytes: 0,
                matched_rule: None,
                destination: None,
                action: ActionKind::Skip,
                reason: "probe failed".into(),
            }],
        };
        let run = execute_backfill(&report);
        assert_eq!(run.applied, 0);
        assert_eq!(run.skipped, 1);
        assert_eq!(run.errored, 0);
    }

    #[test]
    fn backfill_run_round_trips_through_json() {
        let r = BackfillRun {
            folder: "/in".into(),
            scanned: 3,
            applied: 2,
            skipped: 1,
            errored: 0,
            started_at: 100,
            finished_at: 200,
            per_file: vec![],
        };
        let j = serde_json::to_string(&r).unwrap();
        let back: BackfillRun = serde_json::from_str(&j).unwrap();
        assert_eq!(r, back);
    }

    // ─── execute_backfill_streaming + CancelFlag (v3.39 round-10) ───

    /// Smoke test: every file produces exactly one progress frame,
    /// the running tallies match the final run, and the last frame
    /// has processed == total. Pins the contract the UI relies on.
    #[test]
    fn streaming_emits_one_progress_per_file_and_final_frame() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["a.pdf", "b.pdf", "c.pdf"]);
        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        assert_eq!(report.scanned, 3);

        let mut frames: Vec<BackfillProgress> = Vec::new();
        let cancel = CancelFlag::new();
        let run = execute_backfill_streaming(&report, &cancel, |p| frames.push(p.clone()));

        assert_eq!(frames.len(), 3, "one frame per planned file");
        assert_eq!(frames[0].processed, 1);
        assert_eq!(frames[1].processed, 2);
        assert_eq!(frames[2].processed, 3);
        for f in &frames {
            assert_eq!(f.total, 3);
        }
        assert_eq!(frames.last().unwrap().applied, 3);
        assert_eq!(run.applied, 3);
        assert_eq!(run.per_file.len(), 3);
    }

    /// Empty report still emits exactly ONE trailing frame so the UI
    /// has a single transition point out of "applying" — without
    /// this, an empty backfill would be silent and the spinner would
    /// hang until the next state event.
    #[test]
    fn streaming_empty_report_still_emits_one_completion_frame() {
        let report = BackfillReport {
            folder: "/x".into(),
            scanned: 0,
            generated_at: 0,
            planned: vec![],
        };
        let mut frames: Vec<BackfillProgress> = Vec::new();
        let cancel = CancelFlag::new();
        let run = execute_backfill_streaming(&report, &cancel, |p| frames.push(p.clone()));

        assert_eq!(frames.len(), 1);
        assert_eq!(frames[0].processed, 0);
        assert_eq!(frames[0].total, 0);
        assert!(frames[0].current.is_none());
        assert_eq!(run.applied, 0);
    }

    /// Cancelling mid-run: all files queued *after* the flag flips
    /// are stamped Skipped with CANCELLED_REASON; the files that
    /// already ran keep their real outcome. Progress callbacks keep
    /// firing for the cancelled tail so the UI can finish its
    /// progress bar gracefully.
    #[test]
    fn streaming_cancel_stamps_remaining_files_skipped() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["a.pdf", "b.pdf", "c.pdf", "d.pdf"]);
        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);

        let mut frames: Vec<BackfillProgress> = Vec::new();
        let cancel = CancelFlag::new();
        let run = execute_backfill_streaming(&report, &cancel, |p| {
            frames.push(p.clone());
            // Trip the flag after the second file completes.
            if p.processed == 2 {
                cancel.cancel();
            }
        });

        assert_eq!(frames.len(), 4);
        // First two ran for real.
        assert_eq!(frames[0].applied, 1);
        assert_eq!(frames[1].applied, 2);
        // Tail was short-circuited.
        assert_eq!(frames[3].applied, 2);
        assert_eq!(frames[3].skipped, 2);
        assert_eq!(run.applied, 2);
        assert_eq!(run.skipped, 2);
        for o in &run.per_file[2..] {
            assert_eq!(o.status, OutcomeStatus::Skipped);
            assert_eq!(o.error.as_deref(), Some(CANCELLED_REASON));
        }
    }

    /// CancelFlag flipped *before* the first file → entire report is
    /// skipped with CANCELLED_REASON. Edge case in case the user
    /// hits Cancel during the spawn_blocking handoff.
    #[test]
    fn streaming_cancel_flipped_before_start_skips_everything() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["a.pdf", "b.pdf"]);
        let report = plan_backfill(src.path(), &base_watch(out.path()), &[]);

        let mut frames: Vec<BackfillProgress> = Vec::new();
        let cancel = CancelFlag::new();
        cancel.cancel();
        let run = execute_backfill_streaming(&report, &cancel, |p| frames.push(p.clone()));

        assert_eq!(run.applied, 0);
        assert_eq!(run.skipped, 2);
        assert_eq!(frames.len(), 2);
        // Originals must still be on disk — cancel must not move them.
        assert!(src.path().join("a.pdf").exists());
        assert!(src.path().join("b.pdf").exists());
    }

    /// `execute_backfill` (the non-streaming entry point) must stay
    /// behaviour-identical to `execute_backfill_streaming` with a
    /// no-op sink + untripped flag. This pins the delegation so a
    /// future refactor can't quietly fork the two paths.
    #[test]
    fn execute_backfill_matches_streaming_with_noop_progress() {
        let src = tempfile::tempdir().unwrap();
        let out = tempfile::tempdir().unwrap();
        seed_pdfs(src.path(), &["one.pdf", "two.pdf"]);
        let report_a = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        let run_a = execute_backfill(&report_a);
        // Reset by recreating the source files (the first run moved them).
        seed_pdfs(src.path(), &["one.pdf", "two.pdf"]);
        // Drain the output dir so destinations don't disambiguate.
        for entry in fs::read_dir(out.path()).unwrap() {
            fs::remove_file(entry.unwrap().path()).unwrap();
        }
        let report_b = plan_backfill(src.path(), &base_watch(out.path()), &[]);
        let run_b = execute_backfill_streaming(&report_b, &CancelFlag::new(), |_| {});

        assert_eq!(run_a.applied, run_b.applied);
        assert_eq!(run_a.skipped, run_b.skipped);
        assert_eq!(run_a.errored, run_b.errored);
        assert_eq!(run_a.per_file.len(), run_b.per_file.len());
    }

    /// BackfillProgress wire-format pin — the UI counts on these
    /// field names + types being stable. Tripping this test means
    /// a frontend change is required in the same commit.
    #[test]
    fn backfill_progress_round_trips_through_json() {
        let p = BackfillProgress {
            processed: 5,
            total: 10,
            applied: 3,
            skipped: 1,
            errored: 1,
            current: Some(BackfillOutcome {
                source_path: "/in/x.pdf".into(),
                destination: Some("/out/x.pdf".into()),
                status: OutcomeStatus::Moved,
                error: None,
            }),
        };
        let j = serde_json::to_string(&p).unwrap();
        let back: BackfillProgress = serde_json::from_str(&j).unwrap();
        assert_eq!(p, back);
        // Snake_case field-name pin so a renamer can't silently break
        // the wire contract.
        assert!(j.contains("\"processed\":5"));
        assert!(j.contains("\"current\":"));
    }

    /// CancelFlag is cheap to share across threads — verify it
    /// crosses a `move ||` closure and the flip is observed.
    #[test]
    fn cancel_flag_is_clone_and_shared_across_threads() {
        let flag = CancelFlag::new();
        let f2 = flag.clone();
        let h = std::thread::spawn(move || {
            f2.cancel();
        });
        h.join().unwrap();
        assert!(flag.is_cancelled());
    }
}
