import assert from "node:assert/strict";
import { PDFDocument, StandardFonts } from "pdf-lib";
import JSZip from "jszip";
import { mkdtempSync, readFileSync, writeFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { createServer } from "node:net";

const cli=resolve(process.env.SLAB_CLI || `src-tauri/target/debug/slab${process.platform === "win32" ? ".exe" : ""}`);
const serverPath=resolve(process.env.SLAB_SERVER || `src-tauri/target/debug/slab-server${process.platform === "win32" ? ".exe" : ""}`);
const dir=mkdtempSync(join(tmpdir(),"slab-e2e-"));
let checks=0;
function run(args, expected=0) {
  const result=spawnSync(cli,args,{cwd:dir,encoding:"utf8",timeout:30000});
  assert.equal(result.status,expected,`${args[0]}: ${result.error || result.stderr}`); checks++;
  return result.stdout;
}
async function fixture(count) {
  const doc=await PDFDocument.create(); const font=await doc.embedFont(StandardFonts.Helvetica);
  for(let i=0;i<count;i++) doc.addPage([300+i*10,400]).drawText(`Fixture page ${i+1} secret@example.com`,{font,x:20,y:300,size:14});
  doc.setTitle("E2E fixture"); doc.setAuthor("Slab tests");
  return doc.save({useObjectStreams:false});
}
async function pdf(path,count) { const doc=await PDFDocument.load(readFileSync(join(dir,path))); assert.equal(doc.getPageCount(),count,path); checks++; return doc; }
let server;
try {
  const a=await fixture(3), b=await fixture(2);
  writeFileSync(join(dir,"input.pdf"),a); writeFileSync(join(dir,"other.pdf"),b);
  assert.match(run(["version"]),/slab \d/);
  assert.equal(run(["page-count","input.pdf"]).trim(),"3");
  assert.match(run(["extract-text","input.pdf"]),/Fixture page 1/);
  run(["merge","input.pdf","other.pdf","-o",join(dir,"merged.pdf")]); await pdf("merged.pdf",5);
  run(["split-every","input.pdf","2",join(dir,"chunks")]);
  const chunks=readdirSync(join(dir,"chunks")).filter(n=>n.endsWith(".pdf")).sort(); assert.equal(chunks.length,2);
  for(let i=0;i<chunks.length;i++) await pdf(join("chunks",chunks[i]),[2,1][i]);
  run(["split-ranges","input.pdf","1,2-3",join(dir,"ranges")]); assert.equal(readdirSync(join(dir,"ranges")).length,2);
  run(["rotate","input.pdf","1","90","-o",join(dir,"rotated.pdf")]); assert.equal((await pdf("rotated.pdf",3)).getPage(0).getRotation().angle,90);
  // Relative output paths must be supported just like absolute ones.
  run(["rotate","input.pdf","1","90","--permanent","-o","permanent.pdf"]); await pdf("permanent.pdf",3);
  run(["delete-pages","input.pdf","2","-o",join(dir,"trimmed.pdf")]); await pdf("trimmed.pdf",2);
  run(["compress","input.pdf","-o",join(dir,"compressed.pdf")]); await pdf("compressed.pdf",3);
  run(["encrypt","input.pdf","--password","test-only-password","-o",join(dir,"encrypted.pdf")]);
  assert.equal((await PDFDocument.load(readFileSync(join(dir,"encrypted.pdf")),{ignoreEncryption:true})).isEncrypted,true);
  run(["decrypt","encrypted.pdf","--password","wrong-password","-o",join(dir,"wrong.pdf")],1);
  run(["decrypt","encrypted.pdf","--password","test-only-password","-o",join(dir,"decrypted.pdf")]); await pdf("decrypted.pdf",3);
  for(const op of ["grayscale","sanitize","flatten","repair","strip-metadata","reverse","invert"]) {
    run([op,"input.pdf","-o",join(dir,`${op}.pdf`)]); await pdf(`${op}.pdf`,3);
  }
  writeFileSync(join(dir,"doc.md"),"# End to end\n\nA document generated by the native CLI.");
  run(["md2pdf","doc.md","-o",join(dir,"markdown.pdf")]); await pdf("markdown.pdf",1);
  run(["split-every","input.pdf","0",join(dir,"bad-chunks")],1);
  run(["page-count","missing.pdf"],1);
  assert.deepEqual(readFileSync(join(dir,"input.pdf")),Buffer.from(a)); checks++;

  if(process.env.SLAB_SKIP_SERVER!=="1") {
    const probe=createServer(); await new Promise(r=>probe.listen(0,"127.0.0.1",r)); const port=probe.address().port; await new Promise(r=>probe.close(r));
    server=spawn(serverPath,[],{env:{...process.env,SLAB_HOST:"127.0.0.1",SLAB_PORT:String(port)},stdio:["ignore","ignore","pipe"]});
    let serverLog=""; server.stderr.on("data",chunk=>serverLog+=chunk);
    const base=`http://127.0.0.1:${port}`;
    let ready=false;
    for(let i=0;i<100;i++) { try { if((await fetch(base+"/healthz")).ok) {ready=true;break;} } catch {} await new Promise(r=>setTimeout(r,100)); }
    assert.equal(ready,true,`server did not start: ${serverLog}`);
    async function post(op,fields={},files=[{bytes:a,name:"fixture.pdf"}],status=200) {
      const form=new FormData(); for(const file of files) form.append("file",new Blob([file.bytes],{type:"application/pdf"}),file.name);
      for(const [key,value] of Object.entries(fields)) form.append(key,String(value));
      const res=await fetch(`${base}/api/v1/${op}`,{method:"POST",body:form}); assert.equal(res.status,status,`${op}: ${res.status}`); checks++; return res;
    }
    async function resultPdf(op,fields,count,files) { const res=await post(op,fields,files); assert.match(res.headers.get("content-type"),/application\/pdf/); const doc=await PDFDocument.load(await res.arrayBuffer()); assert.equal(doc.getPageCount(),count,op); checks++; return doc; }
    assert.equal((await (await post("page-count")).json()).pages,3);
    await post("info"); assert.match(JSON.stringify(await (await post("extract-text")).json()),/Fixture page 1/);
    await resultPdf("merge",{},5,[{bytes:a,name:"first.pdf"},{bytes:b,name:"second.pdf"}]);
    await resultPdf("rotate",{pages:"1",degrees:"90"},3); await resultPdf("delete-pages",{pages:"2"},2);
    const reordered=await resultPdf("reorder-pages",{order:"3,1,2"},3); assert.equal(reordered.getPage(0).getWidth(),320);
    await resultPdf("compress",{},3); await resultPdf("watermark",{text:"DRAFT"},3); await resultPdf("strip-metadata",{},3);
    const encrypted=await post("encrypt",{password:"server-test"}); const encryptedBytes=new Uint8Array(await encrypted.arrayBuffer());
    await resultPdf("decrypt",{password:"server-test"},3,[{bytes:encryptedBytes,name:"encrypted.pdf"}]);
    for(const [op,fields,counts] of [["split-every",{chunk_size:"2"},[2,1]],["split-ranges",{ranges:"1,2-3"},[1,2]]]) {
      const res=await post(op,fields); const zip=await JSZip.loadAsync(await res.arrayBuffer()); const files=Object.values(zip.files).filter(file=>!file.dir); assert.equal(files.length,2);
      for(let i=0;i<files.length;i++) assert.equal((await PDFDocument.load(await files[i].async("uint8array"))).getPageCount(),counts[i]); checks++;
    }
    await post("merge",{},[{bytes:a,name:"single.pdf"}],400);
    await post("rotate",{pages:"1",degrees:"banana"},undefined,400);
    await post("split-every",{chunk_size:"banana"},undefined,400);
    await post("watermark",{text:"DRAFT",opacity:"banana"},undefined,400);
    const sentinel=join(dir,"outside.pdf"); writeFileSync(sentinel,"untouched");
    await post("page-count",{},[{bytes:a,name:sentinel}]);
    assert.equal(readFileSync(sentinel,"utf8"),"untouched","absolute upload name escaped its temporary directory"); checks++;
    await resultPdf("merge",{},5,[{bytes:a,name:"../first.pdf"},{bytes:b,name:"C:\\uploads\\second.pdf"}]);
    await post("page-count",{},[{bytes:a,name:"../relative.pdf"}]);
    const unicode=await post("rotate",{pages:"1",degrees:"90"},[{bytes:a,name:'résumé "final".pdf'}]);
    assert.match(unicode.headers.get("content-disposition"),/filename\*=UTF-8''/);
  }
  console.log(`Native end-to-end: ${checks} checks passed across CLI PDF round-trips and HTTP API operations.`);
} finally { if(server && server.exitCode === null) { const stopped=new Promise(r=>server.once("exit",r)); server.kill(); await stopped; } rmSync(dir,{recursive:true,force:true}); }
