// Quill Smart Fill — AI mapping layer.
//
// Given a source document's plain text and the target PDF's form
// fields, ask an `AiProvider` to return a strict JSON `{name: value}`
// map and shape it into a [`SmartFillProposal`].
//
// **Robustness contract:**
// - A non-JSON response never bubbles up as an error — it becomes a
//   proposal with all `value: None` entries and a `warnings` line.
//   Rationale: the UI should always render *something*; the user can
//   re-run with a different model.
// - Each field appears in the proposal exactly once, in the same
//   order as the input slice. Missing keys map to `value: None`.
// - Numeric / boolean JSON values are coerced to their string form so
//   the existing `forms::fill` engine (which takes `String`) accepts
//   them as-is.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use crate::ai::{AiError, AiProvider, ChatMessage, ChatOpts, ChatRole};
use crate::pdf::forms::{FieldType, FormField};

/// One target field, as seen by the AI mapper. Strings only — easy
/// for any provider to consume in the prompt.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldSpec {
    pub name: String,
    /// `"text"`, `"button"`, `"choice"`, `"signature"`, `"unknown"`.
    pub kind: String,
    /// Optional human-readable hint (current value, allowed options,
    /// etc.) — gives the model more to anchor on.
    pub hint: Option<String>,
}

impl FieldSpec {
    /// Build a [`FieldSpec`] from the inspector's [`FormField`].
    /// Signature fields are demoted to `unknown` so the mapper won't
    /// try to fill them (signatures need user gesture).
    pub fn from_form_field(f: &FormField) -> Self {
        let kind = match f.field_type {
            FieldType::Text => "text",
            FieldType::Button => "button",
            FieldType::Choice => "choice",
            FieldType::Signature => "signature",
            FieldType::Unknown => "unknown",
        };
        let hint = match f.field_type {
            FieldType::Button | FieldType::Choice if !f.options.is_empty() => {
                Some(format!("options: {}", f.options.join(", ")))
            }
            _ => f.value.clone().map(|v| format!("current: {v}")),
        };
        Self {
            name: f.name.clone(),
            kind: kind.into(),
            hint,
        }
    }
}

/// One row of the proposal — one target field's suggested fill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProposalEntry {
    pub field: String,
    pub value: Option<String>,
    /// 0.0 = none, 0.85 = confident match, 1.0 = exact substring hit.
    pub confidence: f32,
    /// Optional quoted source span supporting this fill (future slice).
    pub source_span: Option<String>,
}

/// The full mapping result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SmartFillProposal {
    pub entries: Vec<ProposalEntry>,
    /// Soft errors — e.g. AI returned non-JSON, model timed out partial.
    /// Surfaced as a yellow banner in the UI.
    pub warnings: Vec<String>,
    /// Which provider answered (for the "Generated by …" footer).
    pub provider: String,
    /// Model identifier echoed by the provider (e.g. `"llama3.2:3b"`).
    pub model: String,
}

/// Ask the AI to map a source document onto the given field specs.
///
/// Always returns `Ok` for parse / shape problems — those become
/// warnings, not errors. The only `Err` cases are genuine provider
/// failures (network, rate-limit, daemon down).
pub async fn propose_fills(
    provider: Arc<dyn AiProvider>,
    source_text: &str,
    fields: &[FieldSpec],
) -> Result<SmartFillProposal, AiError> {
    if fields.is_empty() {
        return Ok(SmartFillProposal {
            entries: Vec::new(),
            warnings: Vec::new(),
            provider: provider.name().into(),
            model: String::new(),
        });
    }
    let prompt = build_prompt(source_text, fields);
    let msgs = vec![
        ChatMessage {
            role: ChatRole::System,
            content: SYSTEM_PROMPT.into(),
        },
        ChatMessage {
            role: ChatRole::User,
            content: prompt,
        },
    ];
    let opts = ChatOpts {
        model: None,
        temperature: Some(0.1),
        max_tokens: Some(1500),
    };
    let resp = provider.chat(&msgs, &opts).await?;

    let (entries, warnings) = parse_mapping(&resp.content, fields, source_text);
    Ok(SmartFillProposal {
        entries,
        warnings,
        provider: provider.name().into(),
        model: resp.model,
    })
}

const SYSTEM_PROMPT: &str = concat!(
    "You are a precise PDF-form field mapper. ",
    "Given a SOURCE document and a list of target FIELDS, ",
    "output a STRICT JSON object whose keys are exactly the field `name` ",
    "values and whose values are strings (or null if no good match in the source). ",
    "Do not include prose, code fences, or explanations. ",
    "Output ONLY the JSON object."
);

fn build_prompt(source_text: &str, fields: &[FieldSpec]) -> String {
    let field_list = serde_json::to_string_pretty(fields).unwrap_or_else(|_| "[]".to_string());
    format!(
        "FIELDS (target PDF form):\n{field_list}\n\nSOURCE document:\n---\n{source_text}\n---\n\nReturn JSON now:"
    )
}

/// Parse the AI's reply into one [`ProposalEntry`] per field. Returns
/// `(entries, warnings)`. If the body isn't a JSON object, every
/// entry's value is `None` and a single warning is emitted.
fn parse_mapping(
    body: &str,
    fields: &[FieldSpec],
    source_text: &str,
) -> (Vec<ProposalEntry>, Vec<String>) {
    let json_slice = extract_json_object(body);
    let parsed: Option<serde_json::Map<String, serde_json::Value>> =
        serde_json::from_str(json_slice).ok();

    let Some(map) = parsed else {
        let entries = fields
            .iter()
            .map(|f| ProposalEntry {
                field: f.name.clone(),
                value: None,
                confidence: 0.0,
                source_span: None,
            })
            .collect();
        return (
            entries,
            vec!["AI response was not valid JSON; could not parse mapping".into()],
        );
    };

    let source_lower = source_text.to_lowercase();
    let mut warnings = Vec::new();
    let mut entries = Vec::with_capacity(fields.len());
    for f in fields {
        let value = map.get(&f.name).and_then(coerce_value);
        let confidence = match value.as_deref() {
            None => 0.0,
            Some("") => 0.0,
            Some(v) => {
                if source_lower.contains(&v.to_lowercase()) {
                    1.0
                } else {
                    0.85
                }
            }
        };
        entries.push(ProposalEntry {
            field: f.name.clone(),
            value,
            confidence,
            source_span: None,
        });
    }

    // Surface unexpected keys as a soft warning so authors can debug
    // prompt drift.
    let extra: Vec<&str> = map
        .keys()
        .filter(|k| !fields.iter().any(|f| &f.name == *k))
        .map(|k| k.as_str())
        .take(5)
        .collect();
    if !extra.is_empty() {
        warnings.push(format!(
            "AI returned {} unknown field(s): {}",
            extra.len(),
            extra.join(", ")
        ));
    }

    (entries, warnings)
}

/// Try to find a JSON object in `body`. Models sometimes wrap their
/// response in ```json fences or add a "Here is the JSON:" preamble —
/// we slice from the first `{` to the matching last `}`.
fn extract_json_object(body: &str) -> &str {
    let trimmed = body.trim();
    let start = match trimmed.find('{') {
        Some(i) => i,
        None => return trimmed,
    };
    let end = match trimmed.rfind('}') {
        Some(i) if i >= start => i,
        _ => return trimmed,
    };
    &trimmed[start..=end]
}

fn coerce_value(v: &serde_json::Value) -> Option<String> {
    match v {
        serde_json::Value::Null => None,
        serde_json::Value::String(s) => Some(s.clone()),
        serde_json::Value::Bool(b) => Some(b.to_string()),
        serde_json::Value::Number(n) => Some(n.to_string()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ai::{AiError, ChatResponse};
    use async_trait::async_trait;
    use std::sync::Mutex;

    struct MockProvider {
        reply: String,
        captured: Mutex<Vec<ChatMessage>>,
    }

    impl MockProvider {
        fn with_response(reply: impl Into<String>) -> Self {
            Self {
                reply: reply.into(),
                captured: Mutex::new(Vec::new()),
            }
        }
    }

    #[async_trait]
    impl AiProvider for MockProvider {
        async fn chat(
            &self,
            msgs: &[ChatMessage],
            _opts: &ChatOpts,
        ) -> Result<ChatResponse, AiError> {
            *self.captured.lock().unwrap() = msgs.to_vec();
            Ok(ChatResponse {
                content: self.reply.clone(),
                model: "mock-mapper:test".into(),
            })
        }
        async fn embed(&self, _texts: &[String]) -> Result<Vec<Vec<f32>>, AiError> {
            unimplemented!()
        }
        fn name(&self) -> &'static str {
            "mock"
        }
    }

    fn fs(name: &str, kind: &str) -> FieldSpec {
        FieldSpec {
            name: name.into(),
            kind: kind.into(),
            hint: None,
        }
    }

    #[tokio::test]
    async fn maps_resume_to_job_app_fields() {
        let provider = Arc::new(MockProvider::with_response(
            r#"{"full_name": "Jane Doe", "email": "jane@example.com", "phone": "+1 555 0100"}"#,
        ));
        let source = "Jane Doe\njane@example.com\n+1 555 0100";
        let fields = vec![
            fs("full_name", "text"),
            fs("email", "text"),
            fs("phone", "text"),
            fs("unrelated", "text"),
        ];
        let p = propose_fills(provider, source, &fields).await.unwrap();
        assert_eq!(p.entries.len(), 4);
        assert_eq!(p.entries[0].value.as_deref(), Some("Jane Doe"));
        // Exact substring → confidence 1.0
        assert!((p.entries[0].confidence - 1.0).abs() < 1e-6);
        assert_eq!(p.entries[1].value.as_deref(), Some("jane@example.com"));
        assert_eq!(p.entries[2].value.as_deref(), Some("+1 555 0100"));
        assert_eq!(p.entries[3].value, None);
        assert_eq!(p.entries[3].confidence, 0.0);
        assert_eq!(p.model, "mock-mapper:test");
        assert_eq!(p.provider, "mock");
    }

    #[tokio::test]
    async fn malformed_ai_json_returns_empty_proposal_with_warning() {
        let provider = Arc::new(MockProvider::with_response("not json at all"));
        let fields = vec![fs("a", "text"), fs("b", "text")];
        let p = propose_fills(provider, "x", &fields).await.unwrap();
        assert_eq!(p.entries.len(), 2);
        assert!(p.entries.iter().all(|e| e.value.is_none()));
        assert_eq!(p.warnings.len(), 1);
        assert!(p.warnings[0].to_lowercase().contains("not valid json"));
    }

    #[tokio::test]
    async fn empty_field_list_returns_empty_proposal_without_calling_provider() {
        let provider = Arc::new(MockProvider::with_response("should-not-be-called"));
        let p = propose_fills(provider.clone(), "anything", &[])
            .await
            .unwrap();
        assert_eq!(p.entries.len(), 0);
        assert_eq!(p.warnings.len(), 0);
        // Provider should NOT have been called.
        assert_eq!(provider.captured.lock().unwrap().len(), 0);
    }

    #[tokio::test]
    async fn coerces_numeric_and_boolean_json_values() {
        let provider = Arc::new(MockProvider::with_response(
            r#"{"age": 42, "agreed": true, "missing": null}"#,
        ));
        let fields = vec![
            fs("age", "text"),
            fs("agreed", "button"),
            fs("missing", "text"),
        ];
        let p = propose_fills(provider, "irrelevant", &fields)
            .await
            .unwrap();
        assert_eq!(p.entries[0].value.as_deref(), Some("42"));
        assert_eq!(p.entries[1].value.as_deref(), Some("true"));
        assert_eq!(p.entries[2].value, None);
    }

    #[tokio::test]
    async fn strips_markdown_fences_around_json() {
        let provider = Arc::new(MockProvider::with_response(
            "Here is the JSON:\n```json\n{\"name\": \"Alice\"}\n```\nHope that helps!",
        ));
        let fields = vec![fs("name", "text")];
        let p = propose_fills(provider, "Alice lives in Paris", &fields)
            .await
            .unwrap();
        assert_eq!(p.entries[0].value.as_deref(), Some("Alice"));
        assert!(p.warnings.is_empty(), "warnings: {:?}", p.warnings);
    }

    #[tokio::test]
    async fn flags_unknown_keys_as_warning_but_still_succeeds() {
        let provider = Arc::new(MockProvider::with_response(
            r#"{"name": "Bob", "extra_key": "ignored"}"#,
        ));
        let fields = vec![fs("name", "text")];
        let p = propose_fills(provider, "Bob", &fields).await.unwrap();
        assert_eq!(p.entries[0].value.as_deref(), Some("Bob"));
        assert_eq!(p.warnings.len(), 1);
        assert!(p.warnings[0].contains("extra_key"));
    }

    #[tokio::test]
    async fn confidence_high_when_value_not_in_source() {
        // AI hallucinated a value not present in the source — we
        // still surface it but at lower confidence so the UI can sort.
        let provider = Arc::new(MockProvider::with_response(
            r#"{"name": "Definitely Not In Source"}"#,
        ));
        let fields = vec![fs("name", "text")];
        let p = propose_fills(provider, "totally unrelated text", &fields)
            .await
            .unwrap();
        assert_eq!(
            p.entries[0].value.as_deref(),
            Some("Definitely Not In Source")
        );
        assert!((p.entries[0].confidence - 0.85).abs() < 1e-6);
    }

    #[tokio::test]
    async fn missing_field_in_ai_response_becomes_none() {
        let provider = Arc::new(MockProvider::with_response(r#"{"a": "1"}"#));
        let fields = vec![fs("a", "text"), fs("b", "text"), fs("c", "text")];
        let p = propose_fills(provider, "1", &fields).await.unwrap();
        assert_eq!(p.entries[0].value.as_deref(), Some("1"));
        assert_eq!(p.entries[1].value, None);
        assert_eq!(p.entries[2].value, None);
    }

    #[tokio::test]
    async fn prompt_includes_system_and_user_message() {
        let provider = Arc::new(MockProvider::with_response(r#"{}"#));
        let fields = vec![fs("a", "text")];
        let _ = propose_fills(provider.clone(), "source", &fields)
            .await
            .unwrap();
        let captured = provider.captured.lock().unwrap();
        assert_eq!(captured.len(), 2);
        assert_eq!(captured[0].role, ChatRole::System);
        assert_eq!(captured[1].role, ChatRole::User);
        assert!(captured[1].content.contains("source"));
        assert!(captured[1].content.contains("\"a\""));
    }

    #[test]
    fn from_form_field_maps_text() {
        let f = FormField {
            name: "x".into(),
            field_type: FieldType::Text,
            value: Some("v".into()),
            page: None,
            rect: None,
            options: vec![],
            read_only: false,
        };
        let s = FieldSpec::from_form_field(&f);
        assert_eq!(s.kind, "text");
        assert_eq!(s.hint.as_deref(), Some("current: v"));
    }

    #[test]
    fn from_form_field_maps_button_with_options() {
        let f = FormField {
            name: "agree".into(),
            field_type: FieldType::Button,
            value: None,
            page: None,
            rect: None,
            options: vec!["Yes".into(), "Off".into()],
            read_only: false,
        };
        let s = FieldSpec::from_form_field(&f);
        assert_eq!(s.kind, "button");
        assert_eq!(s.hint.as_deref(), Some("options: Yes, Off"));
    }
}
